apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.tag }}
  labels:
    app: {{ .Values.image.tag }}
spec:
  ports:
    - port: 9101
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.image.tag }}
