apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"labels":{"k8s-addon":"storage-aws.addons.k8s.io"},"name":"default"},"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs"}
  creationTimestamp: "2018-08-20T21:16:30Z"
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: default
  resourceVersion: "29188271"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/default
  uid: 4eabb7a0-a4be-11e8-bd02-02b2ffdde8d8
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate