apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"false"},"labels":{"k8s-addon":"storage-aws.addons.k8s.io"},"name":"gp2"},"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs"}
    storageclass.beta.kubernetes.io/is-default-class: "false"
  creationTimestamp: "2018-08-20T21:16:30Z"
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: gp2
  resourceVersion: "86084416"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2
  uid: 4ead3a7d-a4be-11e8-bd02-02b2ffdde8d8
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate