allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"k8s-addon":"storage-aws.addons.k8s.io"},"name":"kops-ssd-1-17"},"parameters":{"encrypted":"true","type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.beta.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2020-07-30T05:57:34Z"
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: kops-ssd-1-17
  resourceVersion: "86084417"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/kops-ssd-1-17
  uid: d9c68ef9-57ee-48ad-bb22-34e4b22f0822
parameters:
  encrypted: "true"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer