# Generated by Django 3.2.7 on 2022-01-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every', models.IntegerField(blank=True, null=True, verbose_name='间隔长度')),
                ('period', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
            ],
            options={
                'db_table': 'interval_schedule_table',
            },
        ),
    ]
