# Generated by Django 3.2.7 on 2022-01-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervalschedule',
            options={'managed': False},
        ),
    ]
