# Generated by Django 3.2.7 on 2022-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_intervalschedule_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(blank=True, default='*', max_length=24, null=True, verbose_name='分钟')),
                ('hour', models.CharField(blank=True, default='*', max_length=24, null=True, verbose_name='小时')),
                ('day_of_week', models.CharField(blank=True, default='*', max_length=24, null=True, verbose_name='星期几')),
                ('day_of_month', models.CharField(blank=True, default='*', max_length=24, null=True, verbose_name='几号')),
                ('month_of_year', models.CharField(blank=True, default='*', max_length=24, null=True, verbose_name='月份')),
                ('timezone', models.CharField(blank=True, default='Asia/Shanghai', max_length=24, null=True, verbose_name='时区')),
            ],
            options={
                'db_table': 'django_celery_beat_crontabschedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='任务名称')),
                ('task', models.CharField(blank=True, max_length=200, null=True, verbose_name='任务位置')),
                ('args', models.TextField(null=True, verbose_name='args参数')),
                ('kwargs', models.TextField(null=True, verbose_name='kwargs参数')),
                ('queue', models.CharField(blank=True, max_length=200, null=True, verbose_name='queue')),
                ('exchange', models.CharField(blank=True, max_length=200, null=True, verbose_name='exchange')),
                ('routing_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='routing_key')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('enabled', models.IntegerField(blank=True, null=True, verbose_name='是否启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('total_run_count', models.IntegerField(blank=True, null=True, verbose_name='总运行数')),
                ('date_changed', models.DateTimeField(blank=True, null=True, verbose_name='时间更新')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('crontab_id', models.IntegerField(blank=True, null=True, verbose_name='crontab id')),
                ('interval_id', models.IntegerField(blank=True, null=True, verbose_name='间隔时间表 id')),
                ('solar_id', models.IntegerField(blank=True, null=True, verbose_name='solar id')),
                ('one_off', models.IntegerField(blank=True, null=True, verbose_name='一次运行开关')),
                ('start_time', models.IntegerField(blank=True, null=True, verbose_name='开始时间')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='优先级')),
                ('headers', models.TextField(null=True, verbose_name='headers')),
                ('clocked_id', models.IntegerField(blank=True, null=True, verbose_name='clocked id')),
                ('expire_seconds', models.IntegerField(blank=True, null=True, verbose_name='过期秒数')),
            ],
            options={
                'db_table': 'django_celery_beat_periodictask',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务ID')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务名称')),
                ('task_args', models.TextField(null=True, verbose_name='task_args参数')),
                ('task_kwargs', models.TextField(null=True, verbose_name='task_kwargs参数')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='运行状态')),
                ('worker', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作节点')),
                ('content_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='内容类型')),
                ('content_encoding', models.CharField(blank=True, max_length=64, null=True, verbose_name='编码类型')),
                ('result', models.TextField(null=True, verbose_name='运行结果')),
                ('date_created', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('date_done', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('traceback', models.TextField(null=True, verbose_name='报错跟踪')),
                ('meta', models.TextField(null=True, verbose_name='meta信息')),
            ],
            options={
                'db_table': 'django_celery_results_taskresult',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='intervalschedule',
            table='django_celery_beat_intervalschedule',
        ),
    ]
