apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ca-server","namespace":"altchain"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"ca-server"}}}
  creationTimestamp: "2020-11-01T04:38:41Z"
  name: ca-server
  namespace: altchain
  resourceVersion: "120997697"
  selfLink: /api/v1/namespaces/altchain/services/ca-server
  uid: 692f17ee-c5d7-4338-97dd-852d053287b3
spec:
  clusterIP: 100.66.240.80
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ca-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
