apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"zookeeper","namespace":"kafka"},"spec":{"ports":[{"port":2181,"protocol":"TCP","targetPort":2181}],"selector":{"app":"zookeeper"}}}
  creationTimestamp: "2019-10-15T11:23:15Z"
  name: zookeeper
  namespace: kafka
  resourceVersion: "23212754"
  selfLink: /api/v1/namespaces/kafka/services/zookeeper
  uid: 2e90d117-ef3e-11e9-b4fb-028b91b570fe
spec:
  clusterIP: 100.69.84.2
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
