apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"bminer-operation-webserver-madminer"},"name":"bminer-operation-webserver-madminer","namespace":"bminer"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"bminer-operation-webserver-madminer"}},"template":{"metadata":{"labels":{"app":"bminer-operation-webserver-madminer"}},"spec":{"containers":[{"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/bminer-operation-webserver:madminer-frontend","imagePullPolicy":"Always","name":"bminer-operation-webserver-madminer","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/etc/nginx/conf.d/","name":"config"}]}],"volumes":[{"configMap":{"name":"bminer-operation-webserver-madminer"},"name":"config"}]}}}}
  creationTimestamp: "2021-05-24T08:55:28Z"
  generation: 1
  labels:
    app: bminer-operation-webserver-madminer
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"bminer-operation-webserver-madminer"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":80,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/etc/nginx/conf.d/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"config"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                f:name: {}
    manager: kubectl
    operation: Update
    time: "2021-05-24T08:55:28Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-27T02:22:24Z"
  name: bminer-operation-webserver-madminer
  namespace: bminer
  resourceVersion: "203880745"
  selfLink: /apis/apps/v1/namespaces/bminer/deployments/bminer-operation-webserver-madminer
  uid: eb816b62-4511-4c36-af13-179f4e821073
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bminer-operation-webserver-madminer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bminer-operation-webserver-madminer
    spec:
      containers:
      - image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/bminer-operation-webserver:madminer-frontend
        imagePullPolicy: Always
        name: bminer-operation-webserver-madminer
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bminer-operation-webserver-madminer
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-05-24T08:55:28Z"
    lastUpdateTime: "2021-05-24T08:55:31Z"
    message: ReplicaSet "bminer-operation-webserver-madminer-747c8999" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-27T02:22:24Z"
    lastUpdateTime: "2021-05-27T02:22:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
