apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"bminer-operation-madminer"},"name":"bminer-operation-madminer","namespace":"bminer"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"bminer-operation-madminer"}},"template":{"metadata":{"labels":{"app":"bminer-operation-madminer"}},"spec":{"containers":[{"command":["/app/bminer-operation","-conf","/config/minerops.toml"],"env":[{"name":"AWS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_ACCESS_KEY","name":"aws-athena-credential"}}},{"name":"AWS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_SECRET_KEY","name":"aws-athena-credential"}}}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/bminer-operation:madminer-backend","imagePullPolicy":"Always","name":"bminer-operation","ports":[{"containerPort":8000}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"bminer-operation-madminer"},"name":"config"}]}}}}
  creationTimestamp: "2021-05-24T08:55:28Z"
  generation: 1
  labels:
    app: bminer-operation-madminer
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"bminer-operation"}:
                .: {}
                f:command: {}
                f:env:
                  .: {}
                  k:{"name":"AWS_ACCESS_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AWS_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/config"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"config"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                f:name: {}
    manager: kubectl
    operation: Update
    time: "2021-05-24T08:55:28Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-27T21:26:14Z"
  name: bminer-operation-madminer
  namespace: bminer
  resourceVersion: "204200492"
  selfLink: /apis/apps/v1/namespaces/bminer/deployments/bminer-operation-madminer
  uid: 0116c539-ef11-4dad-85e3-bf435ee94544
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bminer-operation-madminer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bminer-operation-madminer
    spec:
      containers:
      - command:
        - /app/bminer-operation
        - -conf
        - /config/minerops.toml
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: aws-athena-credential
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: aws-athena-credential
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/bminer-operation:madminer-backend
        imagePullPolicy: Always
        name: bminer-operation
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bminer-operation-madminer
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-05-24T08:55:28Z"
    lastUpdateTime: "2021-05-24T08:55:31Z"
    message: ReplicaSet "bminer-operation-madminer-5c7d99ddc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-27T21:26:14Z"
    lastUpdateTime: "2021-05-27T21:26:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
