apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"bminer-backend-staging"},"name":"bminer-backend-staging","namespace":"bminer"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"bminer-backend-staging"}},"template":{"metadata":{"labels":{"app":"bminer-backend-staging"}},"spec":{"containers":[{"args":["/server"],"command":["/app/bminer-backend","-endpoint","0.0.0.0:80","-conf","/config/chord.toml","-staging"],"env":[{"name":"AWS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_ACCESS_KEY","name":"aws-credential"}}},{"name":"AWS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_SECRET_KEY","name":"aws-credential"}}}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/chord:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":80,"scheme":"HTTP"},"initialDelaySeconds":6,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"bminer-backend-staging","ports":[{"containerPort":80,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"bminer-backend"},"name":"config"}]}}}}
  creationTimestamp: "2019-11-18T10:36:02Z"
  generation: 5
  labels:
    app: bminer-backend-staging
  name: bminer-backend-staging
  namespace: bminer
  resourceVersion: "204201214"
  selfLink: /apis/apps/v1/namespaces/bminer/deployments/bminer-backend-staging
  uid: 38012e56-09ef-11ea-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bminer-backend-staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bminer-backend-staging
    spec:
      containers:
      - args:
        - /server
        command:
        - /app/bminer-backend
        - -endpoint
        - 0.0.0.0:80
        - -conf
        - /config/chord.toml
        - -staging
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: aws-credential
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: aws-credential
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/chord:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: bminer-backend-staging
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bminer-backend
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-18T10:36:03Z"
    lastUpdateTime: "2019-11-18T10:36:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
