apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"bminer-backend-prod"},"name":"bminer-backend-prod","namespace":"bminer"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"bminer-backend-prod"}},"template":{"metadata":{"labels":{"app":"bminer-backend-prod"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"args":["/server"],"command":["/app/bminer-backend","-endpoint","0.0.0.0:80","-priv-key","/config/key.json"],"env":[{"name":"AWS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_ACCESS_KEY","name":"aws-credential"}}},{"name":"AWS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_SECRET_KEY","name":"aws-credential"}}}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/chord:prod","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/v1/init/zec/200","port":80,"scheme":"HTTP"},"initialDelaySeconds":6,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"bminer-backend-prod","ports":[{"containerPort":80,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"bminer-backend"},"name":"config"}]}}}}
  creationTimestamp: "2019-10-23T23:55:20Z"
  generation: 14
  labels:
    app: bminer-backend-prod
  name: bminer-backend-prod
  namespace: bminer
  resourceVersion: "198184146"
  selfLink: /apis/apps/v1/namespaces/bminer/deployments/bminer-backend-prod
  uid: 927af4a1-f5f0-11e9-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bminer-backend-prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bminer-backend-prod
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - args:
        - /server
        command:
        - /app/bminer-backend
        - -endpoint
        - 0.0.0.0:80
        - -conf
        - /config/chord.toml
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: aws-credential
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: aws-credential
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/chord:prod
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: bminer-backend-prod
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bminer-backend
        name: config
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-11-18T02:27:11Z"
    lastUpdateTime: "2020-11-18T02:27:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
