apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mining-pool"},"name":"mining-pool","namespace":"bminer"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mining-pool"}},"template":{"metadata":{"labels":{"app":"mining-pool"}},"spec":{"containers":[{"command":["/app/mining-pool","-conf","/config/mining-pool.toml"],"env":[{"name":"AWS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_ACCESS_KEY","name":"aws-athena-credential"}}},{"name":"AWS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_SECRET_KEY","name":"aws-athena-credential"}}}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/mining-pool:prod","imagePullPolicy":"Always","name":"mining-pool","ports":[{"containerPort":8000}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"mining-pool"},"name":"config"}]}}}}
  creationTimestamp: "2020-10-16T05:54:54Z"
  generation: 3
  labels:
    app: mining-pool
  name: mining-pool
  namespace: bminer
  resourceVersion: "204201305"
  selfLink: /apis/apps/v1/namespaces/bminer/deployments/mining-pool
  uid: e1e72eca-7c76-4fd7-a975-59810cf8e524
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mining-pool
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mining-pool
    spec:
      containers:
      - command:
        - /app/mining-pool
        - -conf
        - /config/mining-pool.toml
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: aws-athena-credential
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: aws-athena-credential
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/mining-pool:latest
        imagePullPolicy: Always
        name: mining-pool
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mining-pool
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-16T05:54:54Z"
    lastUpdateTime: "2021-03-15T14:34:19Z"
    message: ReplicaSet "mining-pool-8477649f65" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-27T21:29:10Z"
    lastUpdateTime: "2021-05-27T21:29:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
