apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mining-pool-webserver"},"name":"mining-pool-webserver","namespace":"bminer"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mining-pool-webserver"}},"template":{"metadata":{"labels":{"app":"mining-pool-webserver"}},"spec":{"containers":[{"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/mining-pool-webserver:prod","imagePullPolicy":"Always","name":"mining-pool-webserver","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/etc/nginx/conf.d/","name":"config"}]}],"volumes":[{"configMap":{"name":"mining-pool-webserver"},"name":"config"}]}}}}
  creationTimestamp: "2020-10-16T05:54:54Z"
  generation: 2
  labels:
    app: mining-pool-webserver
  name: mining-pool-webserver
  namespace: bminer
  resourceVersion: "204201199"
  selfLink: /apis/apps/v1/namespaces/bminer/deployments/mining-pool-webserver
  uid: b928aa02-07bb-4098-9e6f-1902afb9e13b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mining-pool-webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mining-pool-webserver
    spec:
      containers:
      - image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/mining-pool-webserver:mining_pool_graph_frontend
        imagePullPolicy: Always
        name: mining-pool-webserver
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mining-pool-webserver
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-16T05:54:54Z"
    lastUpdateTime: "2020-10-30T08:17:11Z"
    message: ReplicaSet "mining-pool-webserver-84dd4cbd48" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-27T21:28:51Z"
    lastUpdateTime: "2021-05-27T21:28:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
