apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"stratum-backend-prod"},"name":"stratum-backend-prod","namespace":"bminer"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"stratum-backend-prod"}},"template":{"metadata":{"labels":{"app":"stratum-backend-prod"}},"spec":{"containers":[{"command":["/app/stratum-backend","-conf","/config/production.toml"],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/chord:prod","imagePullPolicy":"Always","name":"stratum-backend-prod","ports":[{"containerPort":443,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/config","name":"config"},{"mountPath":"/certs","name":"certs"}]}],"volumes":[{"name":"certs","secret":{"secretName":"stratum-backend-certificates"}},{"configMap":{"name":"stratum-backend"},"name":"config"}]}}}}
  creationTimestamp: "2020-10-10T04:39:56Z"
  generation: 4
  labels:
    app: stratum-backend-prod
  name: stratum-backend-prod
  namespace: bminer
  resourceVersion: "204200091"
  selfLink: /apis/apps/v1/namespaces/bminer/deployments/stratum-backend-prod
  uid: 5350372c-7670-43fb-a09f-741b59cdcf74
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stratum-backend-prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stratum-backend-prod
    spec:
      containers:
      - command:
        - /app/stratum-backend
        - -conf
        - /config/production.toml
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/chord:prod
        imagePullPolicy: Always
        name: stratum-backend-prod
        ports:
        - containerPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /certs
          name: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: stratum-backend-certificates
      - configMap:
          defaultMode: 420
          name: stratum-backend
        name: config
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-10-10T04:39:56Z"
    lastUpdateTime: "2020-11-02T02:00:10Z"
    message: ReplicaSet "stratum-backend-prod-7dd5fd9fb6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-27T21:24:51Z"
    lastUpdateTime: "2021-05-27T21:24:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
