apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-mysql-pv
  namespace: "" ##
spec:
  storageClassName: devops-mysql
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mysql
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem