apiVersion: v1
kind: Deployment
metadata:
  name: devops-mysql
  namespace: ep-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: devops-mysql
    spec:
      containers:
      - name: devops-mysql
        image: mysql:8.0.27
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:  ##
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-db
              key: CLOVER_MYSQL_PASSWORD
        volumeMounts:
        - name: time-zone
          mountPath: /etc/localtime
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d/my.cnf
      volumes:
      - name: time-zone
        hostPath:
          path: /etc/localtime
      - name: mysql-data
        persistentVolumeClaim:
          claimName: devops-mysql-pvc
      - name: config
        configMap:
          name: devops-mysql-config