apiVersion: v1
kind: Service
metadata:
  name: devops-mysql
  labels: 
    app: devops-mysql
    namespace:""    ##
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    #targetPort: 3306
    nodePort: 3306
  selector:
    name: devops-mysql