apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-mysql-pvc
  namespace: ""
spec:
  storageClassName: devops-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: devops-mysql-pv