apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-mysql-config
  namespace: "ep-devops"
data:
  my.cnf: |-
    [mysqld]
    pid-file = /var/run/mysqld/mysqld.pid
    socket = /var/run/mysqld/mysqld.sock
    datadir = /var/lib/mysql
    max_connections = 1000
    secure_file_priv = /var/lib/mysql
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION