apiVersion: v1
kind: Service
metadata:
  name: bytom
  namespace: default
spec:
  ports:
  - port: 9888
    protocol: TCP
    targetPort: 9888
  selector:
    app: bytom
  sessionAffinity: None
  type: ClusterIP
