apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: jenkins-www
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jenkins-slaves
    nodePort: 30081
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins-master
  sessionAffinity: None
  type: NodePort
