apiVersion: v1
kind: Service
metadata:
  name: kafka-new
  namespace: default
spec:
  externalName: kafka.kafka.svc.cluster.local
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  sessionAffinity: None
  type: ExternalName
