apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31393
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  sessionAffinity: None
  type: NodePort
