apiVersion: v1
kind: Service
metadata:
  name: mariadb-conflux
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30704
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb-conflux
  sessionAffinity: None
  type: NodePort
