apiVersion: v1
kind: Service
metadata:
  name: miningops
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: miningops
  sessionAffinity: None
  type: ClusterIP
