apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: phabricator-service-conflux
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: phab-ssh-conflux
    nodePort: 31325
    port: 2222
    protocol: TCP
    targetPort: 22
  - name: phab-www-conflux
    nodePort: 30574
    port: 80
    protocol: TCP
    targetPort: 80
  - name: phab-https-conflux
    nodePort: 32375
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: phabricator-conflux
  sessionAffinity: None
  type: LoadBalancer
