apiVersion: v1
kind: Service
metadata:
  labels:
    app: openvpn
    chart: openvpn-3.13.1
    heritage: Tiller
    release: waxen-worm
  name: waxen-worm-openvpn
  namespace: default
spec:
  ports:
  - name: openvpn
    port: 8443
    protocol: TCP
    targetPort: 443
  selector:
    app: openvpn
    release: waxen-worm
  sessionAffinity: None
  type: ClusterIP