apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdb-backend
  namespace: ep-devops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cmdb-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cmdb-backend
    spec:
      containers:
        - env:
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: cmdb-django
            - name: DJANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: cmdb-django
            - name: CMDB_BACK_PORT
              valueFrom:
                configMapKeyRef:
                  key: CMDB_BACK_PORT
                  name: cmdb-django
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: cmdb-redis
            - name: REDIS_PASS
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASS
                  name: cmdb-redis
            - name: HELLO_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: HELLO_APP_ID
                  name: f-approval
            - name: HELLO_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  key: HELLO_APP_SECRET
                  name: f-approval
            - name: JENKINS_HOST
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_HOST
                  name: jenkins
            - name: JENKINS_USER
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_USER
                  name: jenkins
            - name: JENKINS_PASSWD
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_PASSWD
                  name: jenkins
            - name: CLOVER_MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_DB
                  name: mysql-db
            - name: CLOVER_MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_USER
                  name: mysql-db
            - name: CLOVER_MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_PASSWORD
                  name: mysql-db
            - name: CLOVER_MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_HOST
                  name: mysql-db
            - name: ALICLOUD_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: ALICLOUD_ACCESS_KEY
                  name: alicloud
            - name: ALICLOUD_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: ALICLOUD_SECRET_KEY
                  name: alicloud
            - name: ENABLE
              valueFrom:
                configMapKeyRef:
                  key: ENABLE
                  name: ldap
            - name: AUTH_LDAP_BIND_DN
              valueFrom:
                configMapKeyRef:
                  key: AUTH_LDAP_BIND_DN
                  name: ldap
            - name: USER_SEARCH
              valueFrom:
                configMapKeyRef:
                  key: USER_SEARCH
                  name: ldap
            - name: AUTH_LDAP_BIND_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: AUTH_LDAP_BIND_PASSWORD
                  name: ldap
            - name: AUTH_LDAP_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  key: AUTH_LDAP_SERVER_URI
                  name: ldap
            - name: ITSMURL
              valueFrom:
                configMapKeyRef:
                  key: ITSMURL
                  name: cmdb-django
            - name: ClOUDFLARE_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: ClOUDFLARE_TOKEN
                  name: cmdb-django
          image: >-
            prod-harbor-registry.cn-shanghai.cr.aliyuncs.com/prod/cmdb-backend:v1.1.18
          imagePullPolicy: IfNotPresent
          name: cmdb-backend
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 2Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 2Gi
              memory: 1500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
