apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-server
  name: deploy-server
  namespace: ep-devops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deploy-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deploy-server
    spec:
      containers:
        - image: >-
            prod-harbor-registry.cn-shanghai.cr.aliyuncs.com/prod/deploy-server:v0.0.1
          imagePullPolicy: IfNotPresent
          name: deploy-server
          ports:
            - containerPort: 16221
              name: grpc
              protocol: TCP
            - containerPort: 8082
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 2Gi
              memory: 1Gi
            requests:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/
              name: volume-1647414015704
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: toml
          name: volume-1647414015704
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime

