apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: itsm-backend
  name: itsm-backend
  namespace: ep-devops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: itsm-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: itsm-backend
    spec:
      containers:
        - env:
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: cmdb-django
            - name: DJANGO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: cmdb-django
            - name: HELLO_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: HELLO_APP_ID
                  name: f-approval
            - name: HELLO_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  key: HELLO_APP_SECRET
                  name: f-approval
            - name: JENKINS_HOST
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_HOST
                  name: jenkins
            - name: JENKINS_USER
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_USER
                  name: jenkins
            - name: JENKINS_PASSWD
              valueFrom:
                configMapKeyRef:
                  key: JENKINS_PASSWD
                  name: jenkins
            - name: CLOVER_MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_DB
                  name: mysql-db
            - name: CLOVER_MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_USER
                  name: mysql-db
            - name: CLOVER_MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_PASSWORD
                  name: mysql-db
            - name: CLOVER_MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: CLOVER_MYSQL_HOST
                  name: mysql-db
            - name: ENABLE
              valueFrom:
                configMapKeyRef:
                  key: ENABLE
                  name: ldap
            - name: AUTH_LDAP_BIND_DN
              valueFrom:
                configMapKeyRef:
                  key: AUTH_LDAP_BIND_DN
                  name: ldap
            - name: USER_SEARCH
              valueFrom:
                configMapKeyRef:
                  key: USER_SEARCH
                  name: ldap
            - name: AUTH_LDAP_BIND_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: AUTH_LDAP_BIND_PASSWORD
                  name: ldap
            - name: AUTH_LDAP_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  key: AUTH_LDAP_SERVER_URI
                  name: ldap
            - name: DEPLOY_CHAT_ID
              valueFrom:
                configMapKeyRef:
                  key: DEPLOY_CHAT_ID
                  name: f-approval
            - name: ITSMURL
              valueFrom:
                configMapKeyRef:
                  key: ITSMURL
                  name: cmdb-django
            - name: APPROVAL_INSTANCES_DETAIL
              valueFrom:
                configMapKeyRef:
                  key: APPROVAL_INSTANCES_DETAIL
                  name: f-approval
          image: >-
            prod-harbor-registry.cn-shanghai.cr.aliyuncs.com/prod/itsm-backend:v1.2.15
          imagePullPolicy: IfNotPresent
          name: itsm-backend
          ports:
            - containerPort: 8082
              name: itsm-port
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 2Gi
              memory: 2Gi
            requests:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 1500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime