apiVersion: v1
data:
  AWS_ACCESS_KEY: QUtJQUlQSzZYV0xHSzc3R05XNkE=
  AWS_SECRET_KEY: ZFQwSWxXWlVUTE9OL3pzanBlblFBN3ViSGxwbUhudFA0T2oxQkc3dw==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"AWS_ACCESS_KEY":"QUtJQUlQSzZYV0xHSzc3R05XNkE=","AWS_SECRET_KEY":"ZFQwSWxXWlVUTE9OL3pzanBlblFBN3ViSGxwbUhudFA0T2oxQkc3dw=="},"kind":"Secret","metadata":{"annotations":{},"name":"aws-credential","namespace":"bminer"},"type":"Opaque"}
  creationTimestamp: "2019-10-23T11:37:16Z"
  name: aws-credential
  namespace: bminer
  resourceVersion: "24611917"
  selfLink: /api/v1/namespaces/bminer/secrets/aws-credential
  uid: 7695f7a2-f589-11e9-b4fb-028b91b570fe
type: Opaque
