# Generated by Django 3.2.7 on 2022-01-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_name', models.CharField(default=None, help_text='审批名称', max_length=250, unique=True)),
                ('approval_code', models.CharField(default=None, help_text='审批编码', max_length=250, unique=True)),
                ('open_id', models.CharField(default=None, help_text='open_id', max_length=250, unique=True)),
                ('subscribe', models.SmallIntegerField(default=0, help_text='是否订阅')),
            ],
        ),
        migrations.CreateModel(
            name='FInstanceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_code', models.CharField(default=None, help_text='实例编码', max_length=250, unique=True)),
                ('form', models.TextField(default=None, help_text='表单内容', max_length=2250, unique=True)),
                ('status', models.IntegerField(choices=[(0, '还未发布'), (1, '开始发布'), (2, '拒绝发布'), (3, '发布成功'), (4, '发布失败')], default=0, help_text='发布状态')),
                ('user_id', models.CharField(default=None, help_text='用户ID', max_length=150)),
                ('task_id', models.CharField(default=None, help_text='taskID', max_length=150)),
                ('descriptions', models.CharField(default=None, help_text='描述信息', max_length=250)),
                ('f_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.fapproval')),
            ],
        ),
    ]
