# Generated by Django 3.2.7 on 2022-01-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fapproval',
            name='job_name',
            field=models.CharField(default=None, help_text='jenkins job name', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='finstancevalue',
            name='form',
            field=models.TextField(default=None, help_text='表单内容'),
        ),
    ]
