# Generated by Django 3.2.7 on 2022-01-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20220119_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='FComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, help_text='发表评论用户', max_length=150)),
                ('open_id', models.CharField(default=None, help_text='发表评论用户 open id', max_length=150)),
                ('comment', models.CharField(default=None, help_text='评论内容', max_length=250)),
                ('create_time', models.CharField(default=None, help_text='评论时间', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='节点名称', max_length=150)),
                ('need_approver', models.BooleanField(default=False, help_text='是否发起人自选节点')),
                ('node_id', models.CharField(default=None, help_text='节点 ID', max_length=150)),
                ('custom_node_id', models.CharField(default=None, help_text='节点自定义 ID', max_length=150)),
                ('node_type', models.CharField(choices=[('AND', '会签'), ('OR', '或签'), ('CC_NODE', '抄送节点')], default='AND', help_text='审批方式', max_length=100)),
            ],
        ),
    ]
