# Generated by Django 3.2.7 on 2022-01-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_fcomment_fnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TENANT', '租户内可见'), ('DEPARTMENT', '指定部门'), ('USER', '指定用户'), ('NONE', '任何人都不可见')], default='AND', help_text='可见人类型', max_length=100)),
                ('open_id', models.CharField(default=None, help_text='open id', max_length=150)),
                ('user_id', models.CharField(default=None, help_text='可见人用户 ID', max_length=150)),
            ],
        ),
    ]
