# Generated by Django 3.2.7 on 2022-01-20 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_auto_20220120_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanode',
            name='custom_node_id',
        ),
        migrations.RemoveField(
            model_name='fanode',
            name='node_id',
        ),
    ]
