# Generated by Django 3.2.7 on 2022-01-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_auto_20220120_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faviewers',
            name='f_approval',
        ),
        migrations.AddField(
            model_name='faviewers',
            name='f_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.finstancevalue'),
        ),
    ]
