# Generated by Django 3.2.7 on 2022-01-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_auto_20220120_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAViewers',
            new_name='FIViewers',
        ),
    ]
