# Generated by Django 3.2.7 on 2022-01-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_rename_faviewers_fiviewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiviewers',
            name='open_id',
        ),
        migrations.AddField(
            model_name='fitask',
            name='comment',
            field=models.CharField(default=None, help_text='评论内容', max_length=250),
        ),
        migrations.AlterField(
            model_name='finstancevalue',
            name='status',
            field=models.CharField(choices=[('PENDING', '审批中'), ('APPROVED', '通过'), ('REJECTED', '拒绝'), ('CANCELED', '撤回'), ('DELETED', '删除')], default='PENDING', help_text='审批实例状态', max_length=100),
        ),
    ]
