# Generated by Django 3.2.7 on 2022-01-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0011_auto_20220127_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='finstancevalue',
            name='form',
            field=models.TextField(default='', help_text='临时使用1'),
        ),
        migrations.AddField(
            model_name='finstancevalue',
            name='task_id',
            field=models.CharField(default='', help_text='临时使用2', max_length=150),
        ),
    ]
