# Generated by Django 3.2.7 on 2021-12-24 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('page_perms', models.TextField(null=True)),
                ('created_at', models.CharField(default='', max_length=20)),
                ('del_tag', models.SmallIntegerField(default=0, help_text='删除标识')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, utils.mixins.ModelMixin),
        ),
    ]
