# Generated by Django 3.2.7 on 2022-01-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='robot_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='机器人密钥'),
        ),
        migrations.AddField(
            model_name='user',
            name='robot_url',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='机器人地址'),
        ),
    ]
