apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"bminer-com","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/version":"0.32.0","helm.sh/chart":"ingress-nginx-2.1.0"},"name":"bminer-com-ingress-nginx-controller","namespace":"bminer"}}
  creationTimestamp: "2020-05-10T12:21:01Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: bminer-com
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.32.0
    helm.sh/chart: ingress-nginx-2.1.0
  name: bminer-com-ingress-nginx-controller
  namespace: bminer
  resourceVersion: "63601521"
  selfLink: /api/v1/namespaces/bminer/configmaps/bminer-com-ingress-nginx-controller
  uid: d529b4bf-a75e-4fe3-a0c1-19443dfdca48
