apiVersion: v1
data:
  config.toml: |
    [s3]
    bucket="www.bminercontent.com"
    region="us-west-2"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.toml":"[s3]\nbucket=\"www.bminercontent.com\"\nregion=\"us-west-2\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"progpow-kernel-cleaner","namespace":"bminer"}}
  creationTimestamp: "2020-06-12T02:37:47Z"
  name: progpow-kernel-cleaner
  namespace: bminer
  resourceVersion: "72528745"
  selfLink: /api/v1/namespaces/bminer/configmaps/progpow-kernel-cleaner
  uid: 009a997c-60f8-4892-8640-d21d436e0405
