{
 "title": "test-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "机器总和",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select value from t1 where id=1"
    }
   ]
  },
  {
   "title": "上线比例",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select value from t1 where id=2;\n"
    }
   ]
  },
  { "title": "CPU", "type": "bargauge", "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "memory", "type": "bargauge", "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "space", "type": "bargauge", "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "总资产", "type": "stat", "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  {
   "title": "总算力",
   "type": "stat",
   "description": "aaaa",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mflops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } }
  },
  {
   "title": "Dc Host",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "rawSql": "SELECT dc,total,value from t2" }
   ]
  },
  {
   "title": "Hosts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(hostname)) FROM ( SELECT hostname,first(\"hashrate\") as hashrate FROM \"algorithm\" WHERE dc='AWSC-g4dn.xlarge' AND $timeFilter AND algorithm='ethash' GROUP BY hostname) GROUP BY time(10m) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "算力折线图",
   "type": "graph",
   "description": "get numbers of hosts from influxdb",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "算力轴" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"hashrate\") FROM ( SELECT mean(\"hashrate\") as hashrate FROM \"algorithm\" WHERE dc='AWS-g4dn.xlarge' AND $timeFilter AND algorithm='ethash' GROUP BY hostname,pci_bus_id) GROUP BY time(10m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}