apiVersion: v1
data:
  zoo.cfg: |
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=true
    admin.enableServer=true
    server.1=localhost:2888:3888;2181
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"zoo.cfg":"dataDir=/data\ndataLogDir=/datalog\ntickTime=2000\ninitLimit=5\nsyncLimit=2\nautopurge.snapRetainCount=3\nautopurge.purgeInterval=0\nmaxClientCnxns=60\nstandaloneEnabled=true\nadmin.enableServer=true\nserver.1=localhost:2888:3888;2181\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"zookeeper","namespace":"kafka"}}
  creationTimestamp: "2019-10-15T11:22:31Z"
  name: zookeeper
  namespace: kafka
  resourceVersion: "23212664"
  selfLink: /api/v1/namespaces/kafka/configmaps/zookeeper
  uid: 142427e7-ef3e-11e9-b4fb-028b91b570fe
