# Generated by Django 3.2.7 on 2022-01-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessservices',
            name='service_type',
            field=models.IntegerField(choices=[(1, 'apis'), (2, 'services'), (3, 'web')], default=1, verbose_name='服务类型'),
        ),
    ]
