apiVersion: v1
kind: Secret
metadata:
  name: google-client-id
  namespace: sso
type: Opaque
data:
  client-id: MTkxODY0NzA4NjI3LXRrbGo0MHI1dHE1cnFyOTg2Z2ZjamplMmRmYWd1ZjBjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
