#!/bin/sh

ROOT=/tmp/workeragent
ADDRESS=0x63dcD10DA9c1BA3d24c1847Da08dE74573E1153C
mount --bind /dev $ROOT/dev
mount --bind /proc $ROOT/proc
mount --bind /sys $ROOT/sys
mount -t debugfs debufs $ROOT/sys/kernel/debug

ln -f /etc/resolv.conf $ROOT/etc/resolv.conf
ln -f /usr/bin/workeragent $ROOT/usr/sbin/workeragent


for i in i2c_algo_bit drm amdkcl amd_iommu_v2 amd_sched amdchash amdttm sysimgblt sysfillrect syscopyarea fb_sys_fops drm_kms_helper; do
    chroot $ROOT modprobe $i
done

chroot $ROOT modprobe amdgpu vm_fragment_size=9 vm_update_mode=2 ppfeaturemask=0xffffffff
# hwmon_vid nct6775

echo 0 | tee /sys/module/amdkfd/parameters/noretry

for i in `ls -1d /sys/class/hwmon/hwmon*`; do
    readlink $i/device/driver|grep -q "drivers/nct"
    if [ "$?" -eq 0 ]; then
        for j in 1 2 3; do
            echo 1 > $i/pwm${j}_enable
            echo 180 > $i/pwm${j}
        done
    fi
done

#TOTAL_GPU=$(ls -1d $ROOT/sys/class/drm/card?/device|wc -l)
#i=0
#while [ $i -lt $TOTAL_GPU ]; do
#    echo 2 > $ROOT/sys/class/drm/card$i/device/pp_dpm_sclk
    # For 4.17+ kernel, cap the power to 150W
#    HWMON_DIR=$(ls -1d /sys/class/drm/card$i/device/hwmon/hwmon*)
#    if [ $i -eq 4 -o $i -eq 5 ]; then
#        echo 130000000 > $HWMON_DIR/power1_cap
#    else
#        echo 150000000 > $HWMON_DIR/power1_cap
#    fi
#    i=$((i+1))
#done

ENV_FILE=$ROOT/worker.env
wget -q -O $ENV_FILE http://shepherd-master-ha./api/v1/get-initial-config
if [ "$?" -ne 0 ];then
    echo "get initial config error" > /tmp/error.log
    exit 10
fi

CLOCK=920
POWER_BUDGET=150000000
source $ENV_FILE
# Overwrite voltage to 950 (the default voltage)
VOLTAGE=950

wget -q -O /tmp/pp_table http://shepherd-master-ha./deployments/pp_table_vega56_eth

TOTAL_GPU=$(ls -1d /sys/class/drm/card?/device|wc -l)
i=0
while [ $i -lt $TOTAL_GPU ]; do
    base_dir=/sys/class/drm/card${i}/device
    if [ -f "/tmp/pp_table" ]; then
	    cat /tmp/pp_table > ${base_dir}/pp_table
        [ -f "${base_dir}/power_dpm_force_performance_level" ] && echo "manual" > ${base_dir}/power_dpm_force_performance_level
        [ -f "${base_dir}/pp_od_clk_voltage" ] && echo "m 3 ${CLOCK} ${VOLTAGE}" > ${base_dir}/pp_od_clk_voltage
        echo "c" >  ${base_dir}/pp_od_clk_voltage
        echo 7 > ${base_dir}/pp_dpm_sclk
        echo 3 > ${base_dir}/pp_dpm_mclk
    fi
    HWMON_DIR=$(ls -1d /sys/class/drm/card$i/device/hwmon/hwmon*)
    if [ "x${POWER_BUDGET}" != "x" ]; then
        [ -f "$HWMON_DIR/power1_cap" ] && echo ${POWER_BUDGET} > $HWMON_DIR/power1_cap
    fi
    i=$((i+1))
done

chroot $ROOT /usr/sbin/workeragent service -uuid $UUID -miner $MINER &
chroot $ROOT sh /bminer-current/start.sh