apiVersion: v1
kind: ConfigMap
metadata:
  name: cmdb-frontend-nginx
  namespace: ep-devops
data:
  cmdb.conf: |
    server {
      listen 8080;
      server_name localhost;
      location / {
        root /data/projects/cmdb_frontend/dist;
        index index.html index.htm;
        try_files  $uri $uri/ /index.html;
      }
      location ^~ /api/ {
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://121.43.41.139:8081/;
      }
    }