apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: sso-proxy
  name: sso-proxy
  namespace: sso
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: sso-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: sso-proxy
    spec:
      containers:
      - command:
        - /bin/sso-proxy
        env:
        - name: EMAIL_DOMAIN
          value: alt-chain.io
        - name: UPSTREAM_CONFIGS
          value: /sso/upstream_configs.yml
        - name: PROVIDER_URL
          value: https://sso-auth.corp.alt-chain.io
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: proxy-client-id
              name: proxy-client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: proxy-client-secret
              name: proxy-client-secret
        - name: AUTH_CODE_SECRET
          valueFrom:
            secretKeyRef:
              key: proxy-auth-code-secret
              name: proxy-auth-code-secret
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: proxy-cookie-secret
              name: proxy-cookie-secret
        - name: STATSD_HOST
          value: localhost
        - name: STATSD_PORT
          value: "11111"
        - name: COOKIE_SECURE
          value: "false"
        - name: CLUSTER
          value: dev
        - name: VIRTUAL_HOST
          value: '*.corp.alt-chain.io'
        image: buzzfeed/sso:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 4180
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sso-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 4180
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sso
          name: upstream-configs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: upstream-configs
        name: upstream-configs