apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.tag }}
  labels:
    app: {{ .Values.image.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.image.tag }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.tag }}
    spec:
      containers:
        - name: {{ .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: config
      volumes:
      - configMap:
          defaultMode: 420
          name: platform-nginx
        name: config