apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.tag }}
  labels:
    app: {{ .Values.image.tag }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30180 
  selector:
    app: {{ .Values.image.tag }}
