aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2018-08-20T21:16:04Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: admin
  resourceVersion: "86084827"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/admin
  uid: 3eec4681-a4be-11e8-bd02-02b2ffdde8d8
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  - services/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - delete
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - deletecollection
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - patch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - deletecollection
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - deletecollection
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - replicasets/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - get
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - daemonsets/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - daemonsets/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - deployments/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - deployments/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - replicasets/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets/status
  verbs:
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - list
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch