apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"k8s-addon":"dns-controller.addons.k8s.io"},"name":"kops:dns-controller"},"rules":[{"apiGroups":[""],"resources":["endpoints","services","pods","ingress","nodes"],"verbs":["get","list","watch"]},{"apiGroups":["extensions"],"resources":["ingresses"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2018-08-20T21:16:30Z"
  labels:
    k8s-addon: dns-controller.addons.k8s.io
  name: kops:dns-controller
  resourceVersion: "595"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kops%3Adns-controller
  uid: 4e7ce5a5-a4be-11e8-bd02-02b2ffdde8d8
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - ingress
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch