apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"k8s-addon":"kops-controller.addons.k8s.io"},"name":"kops-controller"},"rules":[{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","watch","patch"]}]}
  creationTimestamp: "2020-07-30T06:01:07Z"
  labels:
    k8s-addon: kops-controller.addons.k8s.io
  name: kops-controller
  resourceVersion: "86084772"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kops-controller
  uid: 363ddb71-44cf-4bc4-9c97-9b75bf548d6c
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch