apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"chord-pool"},"name":"chord-pool","namespace":"blockchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"chord-pool"}},"template":{"metadata":{"labels":{"app":"chord-pool"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"args":["--config","/config/config.toml"],"command":["/app/stratum-frontend"],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/chord-pool:latest","imagePullPolicy":"Always","name":"chord-pool","ports":[{"containerPort":32525,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"chord-pool"},"name":"config"}]}}}}
  creationTimestamp: "2020-10-28T09:13:20Z"
  generation: 6
  labels:
    app: chord-pool
  name: chord-pool
  namespace: blockchain
  resourceVersion: "201045861"
  selfLink: /apis/apps/v1/namespaces/blockchain/deployments/chord-pool
  uid: aa4251ea-a7e1-4962-b731-ada285a02cb0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chord-pool
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chord-pool
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - args:
        - --config
        - /config/config.toml
        command:
        - /app/stratum-frontend
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/stratum-frontend:latest
        imagePullPolicy: Always
        name: chord-pool
        ports:
        - containerPort: 32525
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /cred
          name: cred
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: chord-pool
        name: config
      - name: cred
        secret:
          defaultMode: 420
          secretName: chord-pool
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-30T10:34:39Z"
    lastUpdateTime: "2020-11-03T03:50:53Z"
    message: ReplicaSet "chord-pool-5f7c47c789" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-20T03:29:04Z"
    lastUpdateTime: "2021-05-20T03:29:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
