apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"czz-stratum"},"name":"czz-stratum","namespace":"blockchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"czz-stratum"}},"template":{"metadata":{"labels":{"app":"czz-stratum"}},"spec":{"containers":[{"args":["-conf","/config/config.toml","-coin","czz"],"command":["/app/stratum-frontend"],"env":[{"name":"IRISD_SERVICE_PORT","value":"2325"},{"name":"ALTCHAIN_DATACENTER","value":"yul01"}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/stratum-frontend:latest","imagePullPolicy":"Always","name":"czz-stratum","ports":[{"containerPort":6539,"protocol":"TCP"},{"containerPort":31537,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"czz-stratum"},"name":"config"}]}}}}
  creationTimestamp: "2019-11-08T03:42:13Z"
  generation: 8
  labels:
    app: czz-stratum
  name: czz-stratum
  namespace: blockchain
  resourceVersion: "121352156"
  selfLink: /apis/apps/v1/namespaces/blockchain/deployments/czz-stratum
  uid: c0413bfa-01d9-11ea-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: czz-stratum
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: czz-stratum
    spec:
      containers:
      - args:
        - -conf
        - /config/config.toml
        - -coin
        - czz
        command:
        - /app/stratum-frontend
        env:
        - name: IRISD_SERVICE_PORT
          value: "2325"
        - name: ALTCHAIN_DATACENTER
          value: yul01
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/stratum-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 31537
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: czz-stratum
        ports:
        - containerPort: 6539
          protocol: TCP
        - containerPort: 31537
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: stratum
        name: config
status:
  conditions:
  - lastTransitionTime: "2019-11-08T03:42:13Z"
    lastUpdateTime: "2019-11-08T03:42:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
