apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "36"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"czz"},"name":"czz","namespace":"blockchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"czz"}},"template":{"metadata":{"labels":{"app":"czz"}},"spec":{"containers":[{"args":["--configfile=/dev/null","--datadir=/data","--rpcuser=$(RPC_USER)","--rpcpass=$(RPC_PASSWORD)","--rpclisten=0.0.0.0:8334","--maxpeersperip=32","--maxpeers=1024","--targetoutboundpeers=1024","--addpeer=52.34.19.222","--whitelist=52.34.19.222/32","--externalip=34.220.194.238","--notls"],"command":["/app/docker-entrypoint.sh"],"env":[{"name":"RPC_USER","valueFrom":{"secretKeyRef":{"key":"rpcuser","name":"czz"}}},{"name":"RPC_PASSWORD","valueFrom":{"secretKeyRef":{"key":"rpcpass","name":"czz"}}},{"name":"MINING_ADDR","valueFrom":{"secretKeyRef":{"key":"miningaddr","name":"czz"}}}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/czz:latest","imagePullPolicy":"Always","name":"czz","ports":[{"containerPort":8333,"protocol":"TCP"},{"containerPort":8334,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/data","name":"czz-data"}]}],"volumes":[{"name":"czz-data","persistentVolumeClaim":{"claimName":"czz-fullnode"}}]}}}}
  creationTimestamp: "2019-11-07T03:14:58Z"
  generation: 37
  labels:
    app: czz
  name: czz
  namespace: blockchain
  resourceVersion: "42562881"
  selfLink: /apis/apps/v1/namespaces/blockchain/deployments/czz
  uid: c76999ae-010c-11ea-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: czz
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: czz
    spec:
      containers:
      - args:
        - --configfile=/dev/null
        - --datadir=/data
        - --rpcuser=$(RPC_USER)
        - --rpcpass=$(RPC_PASSWORD)
        - --rpclisten=0.0.0.0:8334
        - --maxpeersperip=32
        - --maxpeers=1024
        - --targetoutboundpeers=1024
        - --addpeer=52.34.19.222
        - --whitelist=52.34.19.222/32
        - --externalip=34.220.194.238
        - --notls
        command:
        - /app/docker-entrypoint.sh
        env:
        - name: RPC_USER
          valueFrom:
            secretKeyRef:
              key: rpcuser
              name: czz
        - name: RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rpcpass
              name: czz
        - name: MINING_ADDR
          valueFrom:
            secretKeyRef:
              key: miningaddr
              name: czz
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/czz:latest
        imagePullPolicy: Always
        name: czz
        ports:
        - containerPort: 8333
          protocol: TCP
        - containerPort: 18883
          protocol: TCP
        - containerPort: 8334
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: czz-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: czz-data
        persistentVolumeClaim:
          claimName: czz-fullnode
status:
  conditions:
  - lastTransitionTime: "2019-11-07T03:14:58Z"
    lastUpdateTime: "2019-11-07T03:14:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 37
