apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"eth-stratum"},"name":"eth-stratum","namespace":"blockchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"eth-stratum"}},"template":{"metadata":{"labels":{"app":"eth-stratum"}},"spec":{"containers":[{"args":["-conf","/config/config.toml","-coin","eth"],"command":["/app/stratum-frontend"],"env":[{"name":"IRISD_SERVICE_PORT","value":"2325"},{"name":"ALTCHAIN_DATACENTER","value":"yul01"}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/stratum-frontend:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":31537},"initialDelaySeconds":60,"periodSeconds":60},"name":"eth-stratum","ports":[{"containerPort":31537,"protocol":"TCP"},{"containerPort":6539,"protocol":"TCP"},{"containerPort":8645,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"stratum"},"name":"config"}]}}}}
  creationTimestamp: "2019-11-29T08:47:44Z"
  generation: 3
  labels:
    app: eth-stratum
  name: eth-stratum
  namespace: blockchain
  resourceVersion: "121352162"
  selfLink: /apis/apps/v1/namespaces/blockchain/deployments/eth-stratum
  uid: e8ff2d43-1284-11ea-bf1c-0296fb953976
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: eth-stratum
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eth-stratum
    spec:
      containers:
      - args:
        - -conf
        - /config/config.toml
        - -coin
        - eth
        command:
        - /app/stratum-frontend
        env:
        - name: IRISD_SERVICE_PORT
          value: "2325"
        - name: ALTCHAIN_DATACENTER
          value: yul01
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/stratum-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 31537
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: eth-stratum
        ports:
        - containerPort: 31537
          protocol: TCP
        - containerPort: 6539
          protocol: TCP
        - containerPort: 8645
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: stratum
        name: config
status:
  conditions:
  - lastTransitionTime: "2019-11-29T08:47:44Z"
    lastUpdateTime: "2019-11-29T08:47:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
