apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"grin-wallet","namespace":"blockchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"grin-wallet"}},"template":{"metadata":{"labels":{"app":"grin-wallet"}},"spec":{"containers":[{"args":["-e","-p","$(PASSPHASE)","-r","http://grin-fullnode.default:3413","listen"],"env":[{"name":"PASSPHASE","valueFrom":{"secretKeyRef":{"key":"passphase","name":"grin-wallet"}}}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/grin-wallet:latest","imagePullPolicy":"Always","name":"grin-wallet","ports":[{"containerPort":3415,"protocol":"TCP"},{"containerPort":13415,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/home/grin/.grin","name":"grin-wallet-data"}]}],"securityContext":{"fsGroup":2000,"runAsNonRoot":true,"runAsUser":1000},"volumes":[{"name":"grin-wallet-data","persistentVolumeClaim":{"claimName":"grin-wallet-pvc"}}]}}}}
  creationTimestamp: "2019-08-28T07:27:46Z"
  generation: 3
  labels:
    app: grin-wallet
  name: grin-wallet
  namespace: blockchain
  resourceVersion: "72037441"
  selfLink: /apis/apps/v1/namespaces/blockchain/deployments/grin-wallet
  uid: 54e5c424-c965-11e9-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grin-wallet
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grin-wallet
    spec:
      containers:
      - args:
        - -e
        - -p
        - $(PASSPHASE)
        - -r
        - http://grin-fullnode.blockchain:3413
        - listen
        env:
        - name: PASSPHASE
          valueFrom:
            secretKeyRef:
              key: passphase
              name: grin-wallet
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/grin-wallet:latest
        imagePullPolicy: Always
        name: grin-wallet
        ports:
        - containerPort: 3415
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/grin/.grin
          name: grin-wallet-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: grin-wallet-data
        persistentVolumeClaim:
          claimName: grin-wallet-pvc
status:
  conditions:
  - lastTransitionTime: "2019-08-28T07:27:46Z"
    lastUpdateTime: "2019-08-28T07:27:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
