apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"pmeer-devfee"},"name":"pmeer-devfee","namespace":"blockchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"pmeer-devfee"}},"template":{"metadata":{"labels":{"app":"pmeer-devfee"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"args":["tcp-listen:9766,fork,reuseaddr","tcp-connect:pmeer.666pool.cn:9766"],"image":"alpine/socat","imagePullPolicy":"Always","name":"pmeer-devfee","ports":[{"containerPort":9766,"protocol":"TCP"}]}]}}}}
  creationTimestamp: "2020-04-13T08:50:30Z"
  generation: 4
  labels:
    app: pmeer-devfee
  name: pmeer-devfee
  namespace: blockchain
  resourceVersion: "182434299"
  selfLink: /apis/apps/v1/namespaces/blockchain/deployments/pmeer-devfee
  uid: e3fc3465-f104-4e57-8dc4-a7e37e1c821a
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: pmeer-devfee
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pmeer-devfee
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - args:
        - tcp-listen:9766,fork,reuseaddr
        - tcp-connect:pmeer.666pool.cn:9766
        image: alpine/socat
        imagePullPolicy: Always
        name: pmeer-devfee
        ports:
        - containerPort: 9766
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-13T08:50:30Z"
    lastUpdateTime: "2020-04-13T08:50:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
