apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"sero-devfee"},"name":"sero-devfee","namespace":"blockchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"sero-devfee"}},"template":{"metadata":{"labels":{"app":"sero-devfee"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"args":["tcp-listen:4200,fork,reuseaddr","tcp-connect:sero.f2pool.com:4200"],"image":"alpine/socat","imagePullPolicy":"Always","name":"sero-devfee","ports":[{"containerPort":4200,"protocol":"TCP"}]}]}}}}
  creationTimestamp: "2020-05-04T22:42:29Z"
  generation: 2
  labels:
    app: sero-devfee
  name: sero-devfee
  namespace: blockchain
  resourceVersion: "190787544"
  selfLink: /apis/apps/v1/namespaces/blockchain/deployments/sero-devfee
  uid: ebe0362e-6940-409c-a341-fe63323dd172
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: sero-devfee
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sero-devfee
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - args:
        - tcp-listen:4200,fork,reuseaddr
        - tcp-connect:sero.f2pool.com:4200
        image: alpine/socat
        imagePullPolicy: Always
        name: sero-devfee
        ports:
        - containerPort: 4200
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-04T22:42:29Z"
    lastUpdateTime: "2020-05-04T22:42:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
