apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"grafana"},"name":"grafana","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"grafana"}},"template":{"metadata":{"labels":{"app":"grafana"}},"spec":{"containers":[{"env":[{"name":"GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS","value":"vertamedia-clickhouse-datasource"}],"image":"grafana/grafana","imagePullPolicy":"Always","name":"grafana","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{"requests":{"cpu":"10m"}},"volumeMounts":[{"mountPath":"/etc/grafana","name":"config","subPath":"kops.prod.alt-chain.net/services/grafana"},{"mountPath":"/var/lib/grafana","name":"grafana-data"}]}],"securityContext":{"fsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"volumes":[{"name":"config","persistentVolumeClaim":{"claimName":"config-pvc"}},{"name":"grafana-data","persistentVolumeClaim":{"claimName":"grafana"}}]}}}}
  creationTimestamp: "2020-07-31T04:34:48Z"
  generation: 1
  labels:
    app: grafana
  name: grafana
  namespace: default
  resourceVersion: "182434565"
  selfLink: /apis/apps/v1/namespaces/default/deployments/grafana
  uid: 0cf7252e-6324-412c-8e09-6b71aa822018
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
          value: vertamedia-clickhouse-datasource
        image: grafana/grafana
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/grafana
          name: config
          subPath: kops.prod.alt-chain.net/services/grafana
        - mountPath: /var/lib/grafana
          name: grafana-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-31T04:34:48Z"
    lastUpdateTime: "2020-07-31T04:35:24Z"
    message: ReplicaSet "grafana-6b6cb98fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-04-05T20:11:19Z"
    lastUpdateTime: "2021-04-05T20:11:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
