apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "34"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"influxdb"},"name":"influxdb","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"influxdb"}},"template":{"metadata":{"labels":{"app":"influxdb"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"image":"influxdb:1.6.6","imagePullPolicy":"IfNotPresent","name":"influxdb","ports":[{"containerPort":8086,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/var/lib/influxdb","name":"influxdb-data"},{"mountPath":"/etc/influxdb","name":"config"}]}],"volumes":[{"name":"influxdb-data","persistentVolumeClaim":{"claimName":"influxdb"}},{"configMap":{"name":"influxdb"},"name":"config"}]}}}}
  creationTimestamp: "2019-10-15T15:03:56Z"
  generation: 34
  labels:
    app: influxdb
  name: influxdb
  namespace: default
  resourceVersion: "190787769"
  selfLink: /apis/apps/v1/namespaces/default/deployments/influxdb
  uid: 0269f1e3-ef5d-11e9-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:1.6.6
        imagePullPolicy: IfNotPresent
        name: influxdb
        ports:
        - containerPort: 8086
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-data
        - mountPath: /etc/influxdb
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb
      - configMap:
          defaultMode: 420
          name: influxdb
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-10-15T15:03:56Z"
    lastUpdateTime: "2019-10-15T15:03:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 34
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
