apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"irisd"},"name":"irisd","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"irisd"}},"template":{"metadata":{"labels":{"app":"irisd"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"command":["/app/irisd","-influxHost","http://influxdb.default:8086","-host","0.0.0.0","-port","2325"],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/irisd:latest","imagePullPolicy":"Always","name":"irisd","ports":[{"containerPort":2325,"protocol":"UDP"}]}]}}}}
  creationTimestamp: "2019-06-21T06:35:38Z"
  generation: 5
  labels:
    app: irisd
  name: irisd
  namespace: default
  resourceVersion: "190787566"
  selfLink: /apis/apps/v1/namespaces/default/deployments/irisd
  uid: c82ff3ec-93ee-11e9-a2a3-02b94c1b9762
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: irisd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: irisd
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - command:
        - /app/irisd
        - -influxHost
        - http://influxdb.default:8086
        - -host
        - 0.0.0.0
        - -port
        - "2325"
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/irisd:latest
        imagePullPolicy: Always
        name: irisd
        ports:
        - containerPort: 2325
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-21T06:35:38Z"
    lastUpdateTime: "2019-06-21T06:35:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
