apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"jenkins-master","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"jenkins-master"}},"spec":{"containers":[{"image":"jenkins/jenkins:lts","imagePullPolicy":"Always","name":"jenkins-master","ports":[{"containerPort":8080},{"containerPort":50000}],"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"}]}],"securityContext":{"fsGroup":1000},"volumes":[{"name":"jenkins-home","persistentVolumeClaim":{"claimName":"jenkins-master-pvc"}}]}}}}
  creationTimestamp: "2018-08-20T21:36:22Z"
  generation: 15
  labels:
    app: jenkins-master
  name: jenkins-master
  namespace: default
  resourceVersion: "182434484"
  selfLink: /apis/apps/v1/namespaces/default/deployments/jenkins-master
  uid: 14f72ba2-a4c1-11e8-bd02-02b2ffdde8d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-master
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: Always
        name: jenkins-master
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-master-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-08-20T21:36:22Z"
    lastUpdateTime: "2018-08-20T21:36:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2018-08-20T21:36:22Z"
    lastUpdateTime: "2020-01-17T06:58:17Z"
    message: ReplicaSet "jenkins-master-5f6c4789d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
