apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"mariadb","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"mariadb"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"image":"mariadb:10.4","imagePullPolicy":"IfNotPresent","name":"mariadb","ports":[{"containerPort":3306}],"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"mariadb-data"},{"mountPath":"/etc/mysql/conf.d","name":"config","subPath":"kops.prod.alt-chain.net/services/mariadb/conf.d"}]}],"volumes":[{"name":"mariadb-data","persistentVolumeClaim":{"claimName":"mariadb-pvc"}},{"name":"config","persistentVolumeClaim":{"claimName":"config-pvc"}}]}}}}
  creationTimestamp: "2018-08-20T23:01:40Z"
  generation: 15
  labels:
    app: mariadb
  name: mariadb
  namespace: default
  resourceVersion: "190787989"
  selfLink: /apis/apps/v1/namespaces/default/deployments/mariadb
  uid: ff958edc-a4cc-11e8-bd02-02b2ffdde8d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - image: mariadb:10.4
        imagePullPolicy: IfNotPresent
        name: mariadb
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: 20m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-data
        - mountPath: /etc/mysql/conf.d
          name: config
          subPath: kops.prod.alt-chain.net/services/mariadb/conf.d
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-08-20T23:01:40Z"
    lastUpdateTime: "2018-08-20T23:01:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2018-08-21T01:02:10Z"
    lastUpdateTime: "2020-07-06T08:45:35Z"
    message: ReplicaSet "mariadb-5ccc59b477" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
