apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"miningops","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"miningops"}},"spec":{"containers":[{"command":["/app/mining-operation-portal","-conf","/config/miningops.toml","-miningopsPath","/webapps/miningops"],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/miningops:stage","imagePullPolicy":"Always","name":"miningops","ports":[{"containerPort":8888},{"containerPort":8889}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"miningops-operation-portal"},"name":"config"}]}}}}
  creationTimestamp: "2019-08-26T03:51:33Z"
  generation: 3
  labels:
    app: miningops
  name: miningops
  namespace: default
  resourceVersion: "190782685"
  selfLink: /apis/apps/v1/namespaces/default/deployments/miningops
  uid: cb9b6948-c7b4-11e9-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: miningops
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: miningops
    spec:
      containers:
      - command:
        - /app/mining-operation-portal
        - -conf
        - /config/miningops.toml
        - -miningopsPath
        - /webapps/miningops
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/miningops
        imagePullPolicy: Always
        name: miningops
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 8889
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: miningops-operation-portal
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-08-26T03:51:33Z"
    lastUpdateTime: "2019-08-26T03:51:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
