apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"nfs-client-provisioner","namespace":"default"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"nfs-client-provisioner"}},"spec":{"containers":[{"env":[{"name":"PROVISIONER_NAME","value":"fuseim.pri/ifs"},{"name":"NFS_SERVER","value":"fs-51d587f8.efs.us-west-2.amazonaws.com"},{"name":"NFS_PATH","value":"/"}],"image":"quay.io/external_storage/nfs-client-provisioner:latest","name":"nfs-client-provisioner","volumeMounts":[{"mountPath":"/persistentvolumes","name":"aws-efs-root"}]}],"serviceAccountName":"nfs-client-provisioner","volumes":[{"name":"aws-efs-root","nfs":{"path":"/","server":"fs-51d587f8.efs.us-west-2.amazonaws.com"}}]}}}}
  creationTimestamp: "2018-08-21T00:56:12Z"
  generation: 1
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
  namespace: default
  resourceVersion: "182434327"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nfs-client-provisioner
  uid: fff5cc9f-a4dc-11e8-bd02-02b2ffdde8d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: fuseim.pri/ifs
        - name: NFS_SERVER
          value: fs-51d587f8.efs.us-west-2.amazonaws.com
        - name: NFS_PATH
          value: /
        image: quay.io/external_storage/nfs-client-provisioner:latest
        imagePullPolicy: Always
        name: nfs-client-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: aws-efs-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-client-provisioner
      serviceAccountName: nfs-client-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: aws-efs-root
        nfs:
          path: /
          server: fs-51d587f8.efs.us-west-2.amazonaws.com
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-08-21T00:56:12Z"
    lastUpdateTime: "2018-08-21T00:56:19Z"
    message: ReplicaSet "nfs-client-provisioner-74c7d4c775" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-04-05T20:10:37Z"
    lastUpdateTime: "2021-04-05T20:10:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
