apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"phabricator","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"phabricator"}},"spec":{"containers":[{"env":[{"name":"MYSQL_HOST","value":"mariadb"},{"name":"MYSQL_USER","value":"phabricator"},{"name":"MYSQL_PASS","valueFrom":{"secretKeyRef":{"key":"MYSQL_PASS","name":"phabricator-secret"}}},{"name":"MYSQL_PORT","value":"3306"},{"name":"PHABRICATOR_HOST_KEYS_PATH","value":"/data/hostkeys/persisted"},{"name":"PHABRICATOR_REPOSITORY_PATH","value":"/data/repos"},{"name":"PHABRICATOR_STORAGE_PATH","value":"/data/files"},{"name":"PHABRICATOR_STORAGE_TYPE","value":"disk"},{"name":"PHABRICATOR_HOST","value":"code.corp.alt-chain.io"},{"name":"PHABRICATOR_CDN","value":"code.altchaininternal.com"},{"name":"ENABLE_APCU","value":"true"},{"name":"SSL_TYPE","value":"external"},{"name":"SCRIPT_BEFORE_MIGRATION","value":"/customization/mailgun.sh"}],"image":"redpointgames/phabricator","imagePullPolicy":"Always","name":"phabricator","ports":[{"containerPort":80},{"containerPort":22}],"volumeMounts":[{"mountPath":"/data","name":"data","subPath":"data"},{"mountPath":"/customization","name":"data","subPath":"customization"}]}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"phabricator-pvc"}}]}}}}
  creationTimestamp: "2019-06-06T06:41:38Z"
  generation: 8
  labels:
    app: phabricator
  name: phabricator
  namespace: default
  resourceVersion: "190788084"
  selfLink: /apis/apps/v1/namespaces/default/deployments/phabricator
  uid: 22baa051-8826-11e9-a05a-021598fc403c
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: phabricator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phabricator
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: mariadb
        - name: MYSQL_USER
          value: phabricator
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASS
              name: phabricator-secret
        - name: MYSQL_PORT
          value: "3306"
        - name: PHABRICATOR_HOST_KEYS_PATH
          value: /data/hostkeys/persisted
        - name: PHABRICATOR_REPOSITORY_PATH
          value: /data/repos
        - name: PHABRICATOR_STORAGE_PATH
          value: /data/files
        - name: PHABRICATOR_STORAGE_TYPE
          value: disk
        - name: PHABRICATOR_HOST
          value: code.corp.alt-chain.io
        - name: PHABRICATOR_CDN
          value: code.altchaininternal.com
        - name: ENABLE_APCU
          value: "true"
        - name: SSL_TYPE
          value: external
        - name: SCRIPT_BEFORE_MIGRATION
          value: /customization/mailgun.sh
        image: redpointgames/phabricator
        imagePullPolicy: Always
        name: phabricator
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 22
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: data
        - mountPath: /customization
          name: data
          subPath: customization
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: phabricator-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-06T06:41:38Z"
    lastUpdateTime: "2019-06-06T06:41:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
