apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"telemetry","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"telemetry"}},"template":{"metadata":{"labels":{"app":"telemetry"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kops.k8s.io/instancegroup","operator":"In","values":["online-svc"]}]},"weight":1}]}},"containers":[{"env":[{"name":"GODEBUG","value":"netdns=go"},{"name":"CLICKHOUSE_USER","valueFrom":{"secretKeyRef":{"key":"CLICKHOUSE_USER","name":"telemetry"}}},{"name":"CLICKHOUSE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"CLICKHOUSE_PASSWORD","name":"telemetry"}}},{"name":"AWS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_ACCESS_KEY","name":"aws-athena-credential"}}},{"name":"AWS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_SECRET_KEY","name":"aws-athena-credential"}}}],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/telemetry-deploy:latest","name":"telemetry","resources":{"limits":{"cpu":"40m","memory":"512Mi"},"requests":{"cpu":"20m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"configMap":{"name":"telemetry"},"name":"config"}]}}}}
  creationTimestamp: "2019-04-26T06:59:14Z"
  generation: 18
  labels:
    app: telemetry
  name: telemetry
  namespace: default
  resourceVersion: "203593049"
  selfLink: /apis/apps/v1/namespaces/default/deployments/telemetry
  uid: cd4101a0-67f0-11e9-bd02-02b2ffdde8d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: telemetry
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: telemetry
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - env:
        - name: GODEBUG
          value: netdns=go
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              key: CLICKHOUSE_USER
              name: telemetry
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: CLICKHOUSE_PASSWORD
              name: telemetry
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: aws-athena-credential
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: aws-athena-credential
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/telemetry-deploy:auto_resolve
        imagePullPolicy: Always
        name: telemetry
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 40m
            memory: 512Mi
          requests:
            cpu: 20m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: telemetry
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-04-26T06:59:14Z"
    lastUpdateTime: "2021-02-02T05:48:10Z"
    message: ReplicaSet "telemetry-7674fbdd5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-26T09:11:35Z"
    lastUpdateTime: "2021-05-26T09:11:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 18
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
