apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2019-06-20T08:40:34Z"
  generation: 2
  labels:
    app: openvpn
    chart: openvpn-3.13.1
    heritage: Tiller
    release: waxen-worm
  name: waxen-worm-openvpn
  namespace: default
  resourceVersion: "182434388"
  selfLink: /apis/apps/v1/namespaces/default/deployments/waxen-worm-openvpn
  uid: 11d24800-9337-11e9-a2a3-02b94c1b9762
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openvpn
      release: waxen-worm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 0744b78167a7c4307a3fb9c7ec6357c13f49afdfaca0113e9799557e92d67c80
      creationTimestamp: null
      labels:
        app: openvpn
        release: waxen-worm
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - command:
        - /etc/openvpn/setup/configure.sh
        image: jfelten/openvpn-docker:1.1.0
        imagePullPolicy: IfNotPresent
        name: openvpn
        ports:
        - containerPort: 443
          name: openvpn
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/openvpn/setup
          name: openvpn
        - mountPath: /etc/openvpn/certs
          name: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 509
          name: waxen-worm-openvpn
        name: openvpn
      - name: certs
        persistentVolumeClaim:
          claimName: waxen-worm-openvpn
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-10T08:14:27Z"
    lastUpdateTime: "2020-06-10T08:17:49Z"
    message: ReplicaSet "waxen-worm-openvpn-747cccf958" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-04-05T20:10:45Z"
    lastUpdateTime: "2021-04-05T20:10:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
