version: '3'
services:
  stratum-frontend:
    image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/blockchain/stratum-frontend:latest
    ports:
      - "32526:32526"
    command: ["/app/stratum-frontend","--config","/config/config.toml"]
    restart: always
    volumes:
      - /home/svc/config/dc/yul02/stratum-frontend/stratum-frontend:/config
  ssl-proxy:
    image: alpine/socat
    ports:
      - 32525:32525
    links:
      - "stratum-frontend"
    command: ["openssl-listen:32525,cert=/config/cfx-all.bminer.com.pem,fork,reuseaddr,verify=0", "TCP:stratum-frontend:32526"]
    volumes:
      - /home/svc/config/dc/yul02/stratum-frontend/socat:/config