apiVersion: v1
data:
  linear: '{"coresPerReplica":256,"nodesPerReplica":16,"preventSinglePointFailure":true}'
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-27T12:34:29Z"
  name: coredns-autoscaler
  namespace: kube-system
  resourceVersion: "41730958"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns-autoscaler
  uid: 5cfa2a09-4101-11ea-bf1c-0296fb953976
