apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ip-172-20-58-129_306dd15d-6411-40fe-bdeb-376239134f59","leaseDurationSeconds":15,"acquireTime":"2020-11-18T02:10:30Z","renewTime":"2021-05-28T06:20:48Z","leaderTransitions":2}'
  creationTimestamp: "2020-07-30T06:01:22Z"
  name: kops-controller-leader
  namespace: kube-system
  resourceVersion: "204349869"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kops-controller-leader
  uid: 4c5a7f68-6a8f-4d50-84a5-f20ba7f435be
