apiVersion: v1
kind: Service
metadata:
  name: bminer-operation-webserver-staging2
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bminer-operation-webserver-staging2
  sessionAffinity: None
  type: ClusterIP