apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mdump
  name: mdump
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mdump
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mdump
    spec:
      containers:
      - env:
        - name: worker
          valueFrom:
            secretKeyRef:
              key: worker
              name: mdump-secret
        - name: shepherd
          valueFrom:
            secretKeyRef:
              key: shepherd
              name: mdump-secret
        - name: bminer
          valueFrom:
            secretKeyRef:
              key: bminer
              name: mdump-secret
        - name: miningops
          valueFrom:
            secretKeyRef:
              key: miningops
              name: mdump-secret
        - name: pool
          valueFrom:
            secretKeyRef:
              key: pool
              name: mdump-secret
      - args:
        - -c
        - while true; do echo "Start dump.";/app/mdump;sleep 43200;done
        command:
        - /bin/bash
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/reporters:mdump.v1
        imagePullPolicy: Always
        name: mdump
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/dbback
          name: dbback
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dbback
        persistentVolumeClaim:
          claimName: dbback
