apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"cfx-devfee","namespace":"blockchain","resourceVersion":"121358329","selfLink":"/api/v1/namespaces/blockchain/services/cfx-devfee","uid":"43525a33-9f47-49c0-8ca2-62a8cb99143e"},"spec":{"ports":[{"name":"stratum","port":32525,"protocol":"TCP","targetPort":32525}],"selector":{"app":"chord-pool"},"sessionAffinity":"None","type":"LoadBalancer"}}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:313557088125:certificate/b3561f6c-9d9c-45f3-a060-3acfb82aaf75
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "32525"
  creationTimestamp: "2020-10-28T09:15:23Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: cfx-devfee
  namespace: blockchain
  resourceVersion: "121369244"
  selfLink: /api/v1/namespaces/blockchain/services/cfx-devfee
  uid: 43525a33-9f47-49c0-8ca2-62a8cb99143e
spec:
  clusterIP: 100.71.33.107
  externalTrafficPolicy: Cluster
  ports:
  - name: stratum
    nodePort: 30643
    port: 32525
    protocol: TCP
    targetPort: 32525
  selector:
    app: chord-pool
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a43525a339f4749c08ca262a8cb99143-571312337.us-west-2.elb.amazonaws.com
