apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"etc-devfee","namespace":"blockchain"},"spec":{"ports":[{"port":18118,"protocol":"TCP"}],"selector":{"app":"etc-devfee"}}}
  creationTimestamp: "2021-01-15T22:58:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":18118,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-01-15T22:58:37Z"
  name: etc-devfee
  namespace: blockchain
  resourceVersion: "150704501"
  selfLink: /api/v1/namespaces/blockchain/services/etc-devfee
  uid: d395aaf3-cf82-4eb4-93d4-b7865e67b1ec
spec:
  clusterIP: 100.69.205.114
  ports:
  - port: 18118
    protocol: TCP
    targetPort: 18118
  selector:
    app: etc-devfee
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
