apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ethereum","namespace":"blockchain"},"spec":{"ports":[{"name":"p2p","port":30303,"protocol":"TCP"},{"name":"json-rpc","port":8545,"protocol":"TCP"}],"selector":{"app":"ethereum"}}}
  creationTimestamp: "2019-11-25T10:46:14Z"
  name: ethereum
  namespace: blockchain
  resourceVersion: "30374960"
  selfLink: /api/v1/namespaces/blockchain/services/ethereum
  uid: cd45a500-0f70-11ea-bf1c-0296fb953976
spec:
  clusterIP: 100.71.206.39
  ports:
  - name: p2p
    port: 30303
    protocol: TCP
    targetPort: 30303
  - name: json-rpc
    port: 8545
    protocol: TCP
    targetPort: 8545
  selector:
    app: ethereum
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
