apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"grin-wallet","namespace":"blockchain"},"spec":{"ports":[{"name":"wallet","port":3415,"protocol":"TCP","targetPort":3415}],"selector":{"app":"grin-wallet"}}}
  creationTimestamp: "2020-03-25T11:04:14Z"
  name: grin-wallet
  namespace: blockchain
  resourceVersion: "52234851"
  selfLink: /api/v1/namespaces/blockchain/services/grin-wallet
  uid: e4255ac2-0ab7-4299-b73a-10617b2783e9
spec:
  clusterIP: 100.70.86.123
  ports:
  - name: wallet
    port: 3415
    protocol: TCP
    targetPort: 3415
  selector:
    app: grin-wallet
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
