apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"qitmeer-fullnode","namespace":"blockchain"},"spec":{"ports":[{"name":"p2p","port":8130,"protocol":"TCP","targetPort":8130},{"name":"rpc","port":8131,"protocol":"TCP","targetPort":8131}],"selector":{"app":"qitmeer-fullnode"}}}
  creationTimestamp: "2020-04-13T23:26:14Z"
  name: qitmeer-fullnode
  namespace: blockchain
  resourceVersion: "56287734"
  selfLink: /api/v1/namespaces/blockchain/services/qitmeer-fullnode
  uid: 91a76ca9-278a-4feb-a091-e74c6c8ba877
spec:
  clusterIP: 100.66.153.47
  ports:
  - name: p2p
    port: 8130
    protocol: TCP
    targetPort: 8130
  - name: rpc
    port: 8131
    protocol: TCP
    targetPort: 8131
  selector:
    app: qitmeer-fullnode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
