apiVersion: v1
data:
  MYSQL_HOST: bWFyaWFkYg==
  MYSQL_PASS: Nk10UUdja3c=
  MYSQL_USER: cGhhYnJpY2F0b3I=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"MYSQL_HOST":"bWFyaWFkYg==","MYSQL_PASS":"Nk10UUdja3c=","MYSQL_USER":"cGhhYnJpY2F0b3I="},"kind":"Secret","metadata":{"annotations":{},"name":"phabricator-secret","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2018-08-21T21:43:29Z"
  name: phabricator-secret
  namespace: default
  resourceVersion: "296"
  selfLink: /api/v1/namespaces/default/secrets/phabricator-secret
  uid: 3ddb3da6-a58b-11e8-bd02-02b2ffdde8d8
type: Opaque
