apiVersion: v1
data:
  CLICKHOUSE_PASSWORD: MldIdnliblM1dkhzck1KMg==
  CLICKHOUSE_USER: Ym1pbmVy
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CLICKHOUSE_PASSWORD":"MldIdnliblM1dkhzck1KMg==","CLICKHOUSE_USER":"Ym1pbmVy"},"kind":"Secret","metadata":{"annotations":{},"name":"telemetry","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2020-08-04T07:58:13Z"
  name: telemetry
  namespace: default
  resourceVersion: "88197926"
  selfLink: /api/v1/namespaces/default/secrets/telemetry
  uid: 668674e4-22b0-4a20-b06e-0bbc33f869e4
type: Opaque
