apiVersion: v1
data:
  password: Q08yZHVybFZCQjdSeGh5aVd4eGlXRnBkekJ3aWpBaEtEM0lSa2ZQZ2l5MD0=
  username: YWx0Y2hhaW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"Q08yZHVybFZCQjdSeGh5aVd4eGlXRnBkekJ3aWpBaEtEM0lSa2ZQZ2l5MD0=","username":"YWx0Y2hhaW4="},"kind":"Secret","metadata":{"annotations":{},"name":"vds-blockassembler-secret","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2019-07-10T09:38:12Z"
  name: vds-blockassembler-secret
  namespace: default
  resourceVersion: "6122202"
  selfLink: /api/v1/namespaces/default/secrets/vds-blockassembler-secret
  uid: 6f818d4f-a2f6-11e9-b4fb-028b91b570fe
type: Opaque
