apiVersion: v1
data:
  proxy-body-size: 16M
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-21T22:19:11Z"
  name: altchain-ingress-nginx-ingress-controller
  namespace: altchain
  resourceVersion: "66731848"
  selfLink: /api/v1/namespaces/altchain/configmaps/altchain-ingress-nginx-ingress-controller
  uid: 6bbc2214-d1b0-4583-8dbe-863aff3d9d60
