apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"zookeeper"},"name":"zookeeper","namespace":"kafka"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"zookeeper"}},"template":{"metadata":{"labels":{"app":"zookeeper"}},"spec":{"containers":[{"image":"zookeeper:3.5.5","name":"zookeeper","ports":[{"containerPort":2181,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/conf/zoo.cfg","name":"config","subPath":"zoo.cfg"},{"mountPath":"/data","name":"zookeeper-data"},{"mountPath":"/datalog","name":"zookeeper-datalog"}]}],"volumes":[{"configMap":{"name":"zookeeper"},"name":"config"},{"name":"zookeeper-data","persistentVolumeClaim":{"claimName":"zookeeper-data"}},{"name":"zookeeper-datalog","persistentVolumeClaim":{"claimName":"zookeeper-datalog"}}]}}}}
  creationTimestamp: "2019-10-15T11:23:15Z"
  generation: 4
  labels:
    app: zookeeper
  name: zookeeper
  namespace: kafka
  resourceVersion: "190787911"
  selfLink: /apis/apps/v1/namespaces/kafka/deployments/zookeeper
  uid: 2e8dd8b5-ef3e-11e9-b4fb-028b91b570fe
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - online-svc
            weight: 1
      containers:
      - image: zookeeper:3.5.5
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: zookeeper-data
        - mountPath: /datalog
          name: zookeeper-datalog
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: zookeeper
        name: config
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: zookeeper-data
      - name: zookeeper-datalog
        persistentVolumeClaim:
          claimName: zookeeper-datalog
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-10-15T11:23:15Z"
    lastUpdateTime: "2019-10-15T11:23:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
