apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bminer-operation-webserver-staging
  name: bminer-operation-webserver-staging
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bminer-operation-webserver-staging
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bminer-operation-webserver-staging
    spec:
      containers:
      - image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/bminer-operation-webserver:bminer-operation-frontend-staging
        imagePullPolicy: Always
        name: bminer-operation-webserver-staging
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bminer-operation-webserver-staging
        name: config