apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bminer-operation-staging
  name: bminer-operation-staging
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bminer-operation-staging
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bminer-operation-staging
    spec:
      containers:
      - command:
        - /app/bminer-operation
        - -conf
        - /config/minerops.toml
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: aws-athena-credential
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: aws-athena-credential
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/bminer-operation:latest
        imagePullPolicy: Always
        name: bminer-operation
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bminer-operation-staging
        name: config