apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmdb-frontend
  name: cmdb-frontend
  namespace: ep-devops
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: cmdb-frontend
  sessionAffinity: None
