apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmdb-backend
  name: cmdb-backend
  namespace: ep-devops
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: cmdb-backend
  sessionAffinity: None
  type: ClusterIP