apiVersion: v1
kind: Service
metadata:
  name: itsm-backend
  namespace: ep-devops
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8000
  selector:
    app: itsm-backend
  sessionAffinity: None
  type: ClusterIP