apiVersion: v1
kind: Service
metadata:
  name: vssh
  namespace: ep-devops
spec:
  ports:
    - name: frontend
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: backend
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: vssh
  sessionAffinity: None
  type: ClusterIP
