apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: athena-to-clickhouse-bminer-revenue-job
  namespace: data
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /app/athena-to-clickhouse-job
            - -conf
            - /config/bminer-revenue.conf
            env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY
                  name: aws-athena-credential
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_KEY
                  name: aws-athena-credential
            - name: AWS_REGION
              value: us-west-2
            image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/reporters:athena2clickhouse
            imagePullPolicy: Always
            name: athena-to-clickhouse-bminer-revenue-job
            resources:
              limits:
                memory: 256M
              requests:
                memory: 256M
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /config
              name: config
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: athena-to-clickhouse-bminer-revenue-config
            name: config
  schedule: "00 02 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false