apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXjCCAkagAwIBAgIUCix7Bt8Rxkvv6xEUeg09rM+Ax+IwDQYJKoZIhvcNAQEL
    BQAwNzELMAkGA1UEBhMCS1kxDzANBgNVBAoMBkJtaW5lcjEXMBUGA1UEAwwOQm1p
    bmVyIFJvb3QgQ0EwHhcNMjAxMTAzMDI1NTAyWhcNMzAxMTAxMDI1NTAyWjA/MQsw
    CQYDVQQGEwJLWTEPMA0GA1UECgwGQm1pbmVyMR8wHQYDVQQDDBZCbWluZXIgUm9v
    dCBDQSBMZXZlbCAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyzXK
    yZ3G1bCV7FxGdn4S2LGM6a7HvYKqAS6ffqEylEDe18rMvBzj0VJf4BozgGnzBB2y
    /2FWeBiIpxFcnqlynfCmftmDopOyvbmhaaoFuwTS/6O/AbjmdB/zoB4mPBkksBuF
    6EO1gO6BGon0nPHnhCTz88EZe7Yizvlol0LQ8arlYPykNYH4YBKw7mA0P8kaH7pT
    NGbfNETV+8RcUPWfBMNWO+sRSfktjgl7LWIKZAIisPwTaO3kQz3aDV/cOkObKKZJ
    6DICjjT7bhsgbnBxvh4LDmUq20wnUvoZmRno3qbW7RJnhVc07MGmhl3h0tHqh3s7
    yVoGx08ebri98rZwMwIDAQABo1owWDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB
    /wQEAwICBDA1BgNVHR8ELjAsMCqgKKAmhiRodHRwczovL3d3dy5ibWluZXIuY29t
    L3RydXN0L2NybC5wZW0wDQYJKoZIhvcNAQELBQADggEBACI8V7v99XtqKAQTZTY0
    Bo6qf5bC0tBa3QF6t84cUDuqmOs9htn9lhgl3A+cTiSFI7YmoXnmGhJAiM6a4k37
    rf/1+qb2Hthvg4A2NsSKyFhyul0tAVaMbK+vTScGpH+Zt7EJ4KtqvW9u9jESFdWl
    AgZOh656iZiOKIiz6u6bhQGMRO+kzKOmg/bUhLaAlcNXU+A+x9SihB7VM7npJPlP
    GMWMkYFRLFs4nnrFGe4n9Uunlc+0C6Vl9pBUawxinWgXRRdZGaUn2kRodfPj/Pl5
    +xhwVkun63FibnvV5LtwcV/T46v8P7tRuFqIaSI7EC1vqBl9Nu6hdnw2iM7g+1Y5
    bDU=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIC9TCCAd0CFEiEmpkSWllIH61anaZWIS2xUEXkMA0GCSqGSIb3DQEBCwUAMDcx
    CzAJBgNVBAYTAktZMQ8wDQYDVQQKDAZCbWluZXIxFzAVBgNVBAMMDkJtaW5lciBS
    b290IENBMB4XDTIwMTEwMzAxMTYzM1oXDTMwMTEwMTAxMTYzM1owNzELMAkGA1UE
    BhMCS1kxDzANBgNVBAoMBkJtaW5lcjEXMBUGA1UEAwwOQm1pbmVyIFJvb3QgQ0Ew
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQConpCLih8q0ZBcRLR2hg06
    gfTDltqiyy+KIAb2zOl3ckKMnBck6bQi6lV0bJBK0McK7w3pHXe/h9dmpys6ZnDW
    goe8wSj9tzgDMgFK0QQjZ/qSlyuzFzw32AirzZmJXIgRc3BWAUCKhkfes1F0uRyu
    9eE9fOiMjuBkQ0nUlam5NF8TrDQo6CG3trQzYtdgSaIuCJQv3m5YTELBgveTZzps
    6pshr9pawc0blZZdrATZqf27t5FO7Kx/u7s3eHDrvp49hy27XW895m2oXEWMDaPc
    C/VnSxf1RqveLNh1+mFpfSa5JaAKyYPaWiqy0kCPeQWFQ+Y5muk+oHALfappiUol
    AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAFCSUhw1v4glDMf3VwEtAj1BGLeauAFj
    fcB5qmhYR8y+zsf+pfDomPPUdz7lrL76fdc2vkn83VKD02tRs3FWYYQPkCKdnHm6
    4NOJe9I1fkIZpn8AYol3g9l4RalOJ8qJb+EQaZbdOG2qf6rivyXQ/tgvxaFOXGzi
    rLN/LBSzTktyONxCh8bV6LkkdNDeSVwjZO2QIq65x6jRiKCLWJ/eSKJRpvFD9Wdy
    WTu2FddOFXv6wisj2sZ7i5hWSU+ZsCAgND4snQJssdhlgvEyCGpHEex7S0jnmjUL
    WyxnHuTImtEyFaViySav/TfexnF6bxkS50T4vdT5JRRJdrw9C7Ilmfw=
    -----END CERTIFICATE-----
  config.toml: "[cfx]  \nfullnode_uri = \"35.183.19.30:32525\"\nusername = \"test\"\npassword
    = \"\"\ninitial_target = \"000000003fffffff\"\nfrontend_id = \"k8s\"\n\n[stratum]\nlisten
    = \"0.0.0.0:32525\"\nrest_api =\"0.0.0.0:31537\"\n\n[backend]\nclient_cert_file=\"/config/stratum-frontend.crt\"\nclient_key_file=\"/cred/stratum-frontend.key\"\nca_cert_file=\"/config/ca.crt\"\n"
  stratum-frontend.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIUK02gzCDLv1D6785hCTJEXCdY0q8wDQYJKoZIhvcNAQEL
    BQAwPzELMAkGA1UEBhMCS1kxDzANBgNVBAoMBkJtaW5lcjEfMB0GA1UEAwwWQm1p
    bmVyIFJvb3QgQ0EgTGV2ZWwgMTAeFw0yMDExMDMwMzE5MzBaFw0yMzEwMDQwMzE5
    MzBaMEYxCzAJBgNVBAYTAktZMQ8wDQYDVQQKDAZCbWluZXIxJjAkBgNVBAMMHSou
    c3RyYXR1bS1mcm9udGVuZC5ibWluZXIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA3be61TTAOtX07enoEA/Sdqp8DwU4TnU6/kerp3Rtox7wr4aB
    abKvgTwsVdL4lZFHp4a6CKQ5WvBIF0CuUF7n8qmog6UjdNMNFB0sStLGYiW5WotS
    i0TnCh8WDW/Npd1BXuKcXnUMZ3OhWblfsD57kd24jgEKs6zUOfbzjD1olTlEsFXL
    Q0qvzuWiUXVByD/5AQETcibmPE7iUvPsM7+5zYD7Eje19DXwUzewUa7OyJ2CcQmA
    +W2tt+Q2moAcXmWbnjbgymfAGJLp4jT0/ER1jsViGXNC5YqUAX1bXIsxBytNJ4wl
    xmvwn/wG7+Xywl2FWyQFutn3SW+g1+FA9zVSHwIDAQABozkwNzA1BgNVHR8ELjAs
    MCqgKKAmhiRodHRwczovL3d3dy5ibWluZXIuY29tL3RydXN0L2NybC5wZW0wDQYJ
    KoZIhvcNAQELBQADggEBACqcNmHkzw0HNSvK8p81swPdTHQUvqHBc2u5cRv2GhqQ
    r/dX7qMcNXnr+ZxbO8NeRecH7/gin1gaBFuPXv1UCS/bj868/21cLk0vQg2jSo7X
    HjJ12IDkOGJberWxcysY9VYu9DRiB82fB6/RchNia8B7a+mOlGHoynb35hhgLBur
    r2ort2H6vkIhy9Xoo2fxhs6koJk7HQHCE30IPp8aAKN0RujR769HRdVUL/vZeNZ2
    KcNf8SmkrAO6sZgHPkX8+78NOZw+RTv4ET24k2TYur6jV+oxw5MhuWjlH2nVSUal
    cmdjgvcQj5uRecXVTg4CHkXv2XYtqkFDjpOZT2c5F5I=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ca.crt":"-----BEGIN CERTIFICATE-----\nMIIDXjCCAkagAwIBAgIUCix7Bt8Rxkvv6xEUeg09rM+Ax+IwDQYJKoZIhvcNAQEL\nBQAwNzELMAkGA1UEBhMCS1kxDzANBgNVBAoMBkJtaW5lcjEXMBUGA1UEAwwOQm1p\nbmVyIFJvb3QgQ0EwHhcNMjAxMTAzMDI1NTAyWhcNMzAxMTAxMDI1NTAyWjA/MQsw\nCQYDVQQGEwJLWTEPMA0GA1UECgwGQm1pbmVyMR8wHQYDVQQDDBZCbWluZXIgUm9v\ndCBDQSBMZXZlbCAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyzXK\nyZ3G1bCV7FxGdn4S2LGM6a7HvYKqAS6ffqEylEDe18rMvBzj0VJf4BozgGnzBB2y\n/2FWeBiIpxFcnqlynfCmftmDopOyvbmhaaoFuwTS/6O/AbjmdB/zoB4mPBkksBuF\n6EO1gO6BGon0nPHnhCTz88EZe7Yizvlol0LQ8arlYPykNYH4YBKw7mA0P8kaH7pT\nNGbfNETV+8RcUPWfBMNWO+sRSfktjgl7LWIKZAIisPwTaO3kQz3aDV/cOkObKKZJ\n6DICjjT7bhsgbnBxvh4LDmUq20wnUvoZmRno3qbW7RJnhVc07MGmhl3h0tHqh3s7\nyVoGx08ebri98rZwMwIDAQABo1owWDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB\n/wQEAwICBDA1BgNVHR8ELjAsMCqgKKAmhiRodHRwczovL3d3dy5ibWluZXIuY29t\nL3RydXN0L2NybC5wZW0wDQYJKoZIhvcNAQELBQADggEBACI8V7v99XtqKAQTZTY0\nBo6qf5bC0tBa3QF6t84cUDuqmOs9htn9lhgl3A+cTiSFI7YmoXnmGhJAiM6a4k37\nrf/1+qb2Hthvg4A2NsSKyFhyul0tAVaMbK+vTScGpH+Zt7EJ4KtqvW9u9jESFdWl\nAgZOh656iZiOKIiz6u6bhQGMRO+kzKOmg/bUhLaAlcNXU+A+x9SihB7VM7npJPlP\nGMWMkYFRLFs4nnrFGe4n9Uunlc+0C6Vl9pBUawxinWgXRRdZGaUn2kRodfPj/Pl5\n+xhwVkun63FibnvV5LtwcV/T46v8P7tRuFqIaSI7EC1vqBl9Nu6hdnw2iM7g+1Y5\nbDU=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIC9TCCAd0CFEiEmpkSWllIH61anaZWIS2xUEXkMA0GCSqGSIb3DQEBCwUAMDcx\nCzAJBgNVBAYTAktZMQ8wDQYDVQQKDAZCbWluZXIxFzAVBgNVBAMMDkJtaW5lciBS\nb290IENBMB4XDTIwMTEwMzAxMTYzM1oXDTMwMTEwMTAxMTYzM1owNzELMAkGA1UE\nBhMCS1kxDzANBgNVBAoMBkJtaW5lcjEXMBUGA1UEAwwOQm1pbmVyIFJvb3QgQ0Ew\nggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQConpCLih8q0ZBcRLR2hg06\ngfTDltqiyy+KIAb2zOl3ckKMnBck6bQi6lV0bJBK0McK7w3pHXe/h9dmpys6ZnDW\ngoe8wSj9tzgDMgFK0QQjZ/qSlyuzFzw32AirzZmJXIgRc3BWAUCKhkfes1F0uRyu\n9eE9fOiMjuBkQ0nUlam5NF8TrDQo6CG3trQzYtdgSaIuCJQv3m5YTELBgveTZzps\n6pshr9pawc0blZZdrATZqf27t5FO7Kx/u7s3eHDrvp49hy27XW895m2oXEWMDaPc\nC/VnSxf1RqveLNh1+mFpfSa5JaAKyYPaWiqy0kCPeQWFQ+Y5muk+oHALfappiUol\nAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAFCSUhw1v4glDMf3VwEtAj1BGLeauAFj\nfcB5qmhYR8y+zsf+pfDomPPUdz7lrL76fdc2vkn83VKD02tRs3FWYYQPkCKdnHm6\n4NOJe9I1fkIZpn8AYol3g9l4RalOJ8qJb+EQaZbdOG2qf6rivyXQ/tgvxaFOXGzi\nrLN/LBSzTktyONxCh8bV6LkkdNDeSVwjZO2QIq65x6jRiKCLWJ/eSKJRpvFD9Wdy\nWTu2FddOFXv6wisj2sZ7i5hWSU+ZsCAgND4snQJssdhlgvEyCGpHEex7S0jnmjUL\nWyxnHuTImtEyFaViySav/TfexnF6bxkS50T4vdT5JRRJdrw9C7Ilmfw=\n-----END CERTIFICATE-----\n","config.toml":"[cfx]  \nfullnode_uri = \"35.183.19.30:32525\"\nusername = \"test\"\npassword = \"\"\ninitial_target = \"000000003fffffff\"\nfrontend_id = \"k8s\"\n\n[stratum]\nlisten = \"0.0.0.0:32525\"\nrest_api =\"0.0.0.0:31537\"\n\n[backend]\nclient_cert_file=\"/config/stratum-frontend.crt\"\nclient_key_file=\"/cred/stratum-frontend.key\"\nca_cert_file=\"/config/ca.crt\"\n","stratum-frontend.crt":"-----BEGIN CERTIFICATE-----\nMIIDTDCCAjSgAwIBAgIUK02gzCDLv1D6785hCTJEXCdY0q8wDQYJKoZIhvcNAQEL\nBQAwPzELMAkGA1UEBhMCS1kxDzANBgNVBAoMBkJtaW5lcjEfMB0GA1UEAwwWQm1p\nbmVyIFJvb3QgQ0EgTGV2ZWwgMTAeFw0yMDExMDMwMzE5MzBaFw0yMzEwMDQwMzE5\nMzBaMEYxCzAJBgNVBAYTAktZMQ8wDQYDVQQKDAZCbWluZXIxJjAkBgNVBAMMHSou\nc3RyYXR1bS1mcm9udGVuZC5ibWluZXIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC\nAQ8AMIIBCgKCAQEA3be61TTAOtX07enoEA/Sdqp8DwU4TnU6/kerp3Rtox7wr4aB\nabKvgTwsVdL4lZFHp4a6CKQ5WvBIF0CuUF7n8qmog6UjdNMNFB0sStLGYiW5WotS\ni0TnCh8WDW/Npd1BXuKcXnUMZ3OhWblfsD57kd24jgEKs6zUOfbzjD1olTlEsFXL\nQ0qvzuWiUXVByD/5AQETcibmPE7iUvPsM7+5zYD7Eje19DXwUzewUa7OyJ2CcQmA\n+W2tt+Q2moAcXmWbnjbgymfAGJLp4jT0/ER1jsViGXNC5YqUAX1bXIsxBytNJ4wl\nxmvwn/wG7+Xywl2FWyQFutn3SW+g1+FA9zVSHwIDAQABozkwNzA1BgNVHR8ELjAs\nMCqgKKAmhiRodHRwczovL3d3dy5ibWluZXIuY29tL3RydXN0L2NybC5wZW0wDQYJ\nKoZIhvcNAQELBQADggEBACqcNmHkzw0HNSvK8p81swPdTHQUvqHBc2u5cRv2GhqQ\nr/dX7qMcNXnr+ZxbO8NeRecH7/gin1gaBFuPXv1UCS/bj868/21cLk0vQg2jSo7X\nHjJ12IDkOGJberWxcysY9VYu9DRiB82fB6/RchNia8B7a+mOlGHoynb35hhgLBur\nr2ort2H6vkIhy9Xoo2fxhs6koJk7HQHCE30IPp8aAKN0RujR769HRdVUL/vZeNZ2\nKcNf8SmkrAO6sZgHPkX8+78NOZw+RTv4ET24k2TYur6jV+oxw5MhuWjlH2nVSUal\ncmdjgvcQj5uRecXVTg4CHkXv2XYtqkFDjpOZT2c5F5I=\n-----END CERTIFICATE-----\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cfx-stratum","namespace":"blockchain"}}
  creationTimestamp: "2021-05-08T06:36:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:config.toml: {}
        f:stratum-frontend.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl
    operation: Update
    time: "2021-05-13T01:13:54Z"
  name: cfx-stratum
  namespace: blockchain
  resourceVersion: "198144596"
  selfLink: /api/v1/namespaces/blockchain/configmaps/cfx-stratum
  uid: 63ff0085-dd24-4a47-944a-a8f6ddd8fe02
