# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: djentry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='djentry.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\rserver/clover',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdjentry.proto\"\"\n\x0fUserInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x1f\n\x10UserInfoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2G\n\x11\x44jentryStatistics\x12\x32\n\x0bGetUserInfo\x12\x10.UserInfoRequest\x1a\x11.UserInfoResponseB\x0fZ\rserver/cloverb\x06proto3'
)




_USERINFOREQUEST = _descriptor.Descriptor(
  name='UserInfoRequest',
  full_name='UserInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserInfoRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=51,
)


_USERINFORESPONSE = _descriptor.Descriptor(
  name='UserInfoResponse',
  full_name='UserInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='UserInfoResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['UserInfoRequest'] = _USERINFOREQUEST
DESCRIPTOR.message_types_by_name['UserInfoResponse'] = _USERINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInfoRequest = _reflection.GeneratedProtocolMessageType('UserInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREQUEST,
  '__module__' : 'djentry_pb2'
  # @@protoc_insertion_point(class_scope:UserInfoRequest)
  })
_sym_db.RegisterMessage(UserInfoRequest)

UserInfoResponse = _reflection.GeneratedProtocolMessageType('UserInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERINFORESPONSE,
  '__module__' : 'djentry_pb2'
  # @@protoc_insertion_point(class_scope:UserInfoResponse)
  })
_sym_db.RegisterMessage(UserInfoResponse)


DESCRIPTOR._options = None

_DJENTRYSTATISTICS = _descriptor.ServiceDescriptor(
  name='DjentryStatistics',
  full_name='DjentryStatistics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=86,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserInfo',
    full_name='DjentryStatistics.GetUserInfo',
    index=0,
    containing_service=None,
    input_type=_USERINFOREQUEST,
    output_type=_USERINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DJENTRYSTATISTICS)

DESCRIPTOR.services_by_name['DjentryStatistics'] = _DJENTRYSTATISTICS

# @@protoc_insertion_point(module_scope)
