version: '3'
services:
  pxeserver:
    image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/farm/pxeserver:latest
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: always
    volumes:
      - /home/svc/config/dc/yul02/pxeserver:/config
      - /home/svc/services/pxeserver/data:/data
      - /home/svc/services/pxeserver/logs:/var/log
  
  shepherd:
    image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/farm/shepherd:latest
    restart: always
    network_mode: host
    command: ["/app/shepherd", "-conf", "/home/svc/config/shepherd.json"]
    volumes:
      - /home/svc/config/dc/yul02/shepherd:/config
      - /home/svc/config/dc/yul02/pxeserver/dnsmasq.d/nodes.conf:/config/nodes.conf

  syslog:
    image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/farm/syslog:latest
    restart: always
    #cap_add:
    #  - NET_ADMIN
    network_mode: host
    user: "0:0"
    command: ["-dc", "yul02", "-conf", "/config/nodes.conf"]
    environment:
      - GODEBUG="netdns=cgo"
    volumes:
     # - /home/svc/config/dc/yul02/pxeserver/dnsmasq.d/:/config
      - /home/svc/config/dc/yul02/docker-compose/:/config
      - /etc/hosts:/etc/hosts
    dns:
      - 8.8.8.8
  
  tunnels:
    image: zhegao/autossh
    user: "0:0"
    restart: always
    network_mode: host 
    command:
      - autossh
      - -M
      - "0"
      - -o
      - ExitOnForwardFailure=yes
      - -o
      - ServerAliveCountMax=3
      - -o
      - ServerAliveInterval=10
      - -NT
      - -L
      - 127.0.0.1:9092:100.70.81.93:9092
      - -L
      - 10.3.0.1:8086:100.71.38.14:8086
      - -L
      - 127.0.0.1:2379:100.69.106.78:2379
      - svc@edgegw01-a1.alt-chain.io
    volumes:
      - /home/svc/ssh-tunnel/:/root
    dns:
      - 8.8.8.8

  etcd-grpc-proxy:
    image: bitnami/etcd
    restart: always
    network_mode: host
    command: ["etcd","grpc-proxy","start","--endpoints=127.0.0.1:2379","--listen-addr=10.3.0.1:23790"]
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes