apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ca-server"},"name":"ca-server","namespace":"altchain"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ca-server"}},"template":{"metadata":{"labels":{"app":"ca-server"}},"spec":{"containers":[{"command":["/app/caserver","-endpoint","0.0.0.0:80","-ca","/config/ca_key"],"image":"313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/ca-server:latest","imagePullPolicy":"Always","name":"ca-server","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/config","name":"config"}]}],"volumes":[{"name":"config","secret":{"secretName":"ca-server"}}]}}}}
  creationTimestamp: "2020-11-01T04:38:40Z"
  generation: 3
  labels:
    app: ca-server
  name: ca-server
  namespace: altchain
  resourceVersion: "204200096"
  selfLink: /apis/apps/v1/namespaces/altchain/deployments/ca-server
  uid: dd75fcff-3d1b-43a6-9d4a-3bda0474bf89
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ca-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ca-server
    spec:
      containers:
      - command:
        - /app/caserver
        - -endpoint
        - 0.0.0.0:80
        - -ca
        - /config/ca_key
        image: 313557088125.dkr.ecr.us-west-2.amazonaws.com/alt-chain/ca-server:latest
        imagePullPolicy: Always
        name: ca-server
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: ca-server
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-01T04:38:41Z"
    lastUpdateTime: "2020-11-01T05:15:57Z"
    message: ReplicaSet "ca-server-56f86f8999" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-27T21:24:51Z"
    lastUpdateTime: "2021-05-27T21:24:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
