apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-addon":"dns-controller.addons.k8s.io","k8s-app":"dns-controller","version":"v1.18.2"},"name":"dns-controller","namespace":"kube-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"dns-controller"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-addon":"dns-controller.addons.k8s.io","k8s-app":"dns-controller","version":"v1.18.2"}},"spec":{"containers":[{"command":["/usr/bin/dns-controller","--watch-ingress=false","--dns=aws-route53","--zone=aws.prod.alt-chain.net","--zone=*/*","-v=2"],"env":[{"name":"KUBERNETES_SERVICE_HOST","value":"127.0.0.1"}],"image":"kope/dns-controller:1.18.2","name":"dns-controller","resources":{"requests":{"cpu":"50m","memory":"50Mi"}},"securityContext":{"runAsNonRoot":true}}],"dnsPolicy":"Default","hostNetwork":true,"nodeSelector":{"node-role.kubernetes.io/master":""},"priorityClassName":"system-cluster-critical","serviceAccount":"dns-controller","tolerations":[{"operator":"Exists"}]}}}}
  creationTimestamp: "2018-08-20T21:16:30Z"
  generation: 7
  labels:
    k8s-addon: dns-controller.addons.k8s.io
    k8s-app: dns-controller
    version: v1.18.2
  name: dns-controller
  namespace: kube-system
  resourceVersion: "127692907"
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/dns-controller
  uid: 4e78f535-a4be-11e8-bd02-02b2ffdde8d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: dns-controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-addon: dns-controller.addons.k8s.io
        k8s-app: dns-controller
        version: v1.18.2
    spec:
      containers:
      - command:
        - /usr/bin/dns-controller
        - --watch-ingress=false
        - --dns=aws-route53
        - --zone=aws.prod.alt-chain.net
        - --zone=*/*
        - -v=2
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: 127.0.0.1
        image: kope/dns-controller:1.18.2
        imagePullPolicy: IfNotPresent
        name: dns-controller
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: dns-controller
      serviceAccountName: dns-controller
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-08-20T21:16:30Z"
    lastUpdateTime: "2020-11-18T00:47:14Z"
    message: ReplicaSet "dns-controller-877c67d5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-11-18T02:11:03Z"
    lastUpdateTime: "2020-11-18T02:11:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
