apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"bminer-operation-madminer","namespace":"bminer"},"spec":{"ports":[{"port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"bminer-operation-madminer"},"type":"ClusterIP"}}
  creationTimestamp: "2021-05-24T08:55:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":8000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-05-24T08:55:28Z"
  name: bminer-operation-madminer
  namespace: bminer
  resourceVersion: "202775563"
  selfLink: /api/v1/namespaces/bminer/services/bminer-operation-madminer
  uid: 8668bb67-6099-4267-853c-98284e78beab
spec:
  clusterIP: 100.66.152.79
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: bminer-operation-madminer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
