apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"bminer-operation","namespace":"bminer"},"spec":{"ports":[{"port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"bminer-operation"},"type":"NodePort"}}
  creationTimestamp: "2020-03-16T00:33:39Z"
  name: bminer-operation
  namespace: bminer
  resourceVersion: "95921911"
  selfLink: /api/v1/namespaces/bminer/services/bminer-operation
  uid: 260c7196-7f20-476b-bbd0-2b8a719e4d76
spec:
  clusterIP: 100.68.12.109
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31246
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: bminer-operation
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
