apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"bminer-operation-webserver","namespace":"bminer"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"bminer-operation-webserver"},"type":"NodePort"}}
  creationTimestamp: "2020-03-16T00:33:39Z"
  name: bminer-operation-webserver
  namespace: bminer
  resourceVersion: "95921912"
  selfLink: /api/v1/namespaces/bminer/services/bminer-operation-webserver
  uid: 1ebf1a73-f302-4b74-8fae-fba28e32af84
spec:
  clusterIP: 100.69.119.189
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31881
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bminer-operation-webserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
