apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:313557088125:certificate/cde46c39-a338-4eeb-a110-e65b3e5fa38f
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  creationTimestamp: "2021-05-21T07:54:47Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-21T07:54:49Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {}
          f:service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {}
          f:service.beta.kubernetes.io/aws-load-balancer-ssl-ports: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-05-25T03:34:28Z"
  name: bminer-operation-webserver-staging2
  namespace: bminer
  resourceVersion: "203093728"
  selfLink: /api/v1/namespaces/bminer/services/bminer-operation-webserver-staging2
  uid: fafa0d9a-9564-4503-8dc5-c0f8b4a6804d
spec:
  clusterIP: 100.69.135.136
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31962
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30204
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: bminer-operation-webserver-madminer
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: afafa0d9a956445038dc5c0f8b4a6804-1334783844.us-west-2.elb.amazonaws.com
