apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  type: NodePort
  selector: 
    app: my-app
    release: canary
  ports:
  - name: http
    nodePort: 30327
    port: 80
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deploy
  namespace: default
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: my-app
      release: canary
  template:
    metadata:
      labels:
        app: my-app
        release: canary
    spec:
      containers:
      - name: my-app
        image: ikubernetes/myapp:v2
        ports: 
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
          limits:
            cpu: 128m
            memory: 128Mi