apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: altchain
    traefik.frontend.priority: "2"
  name: jenkins
  namespace: default
spec:
  rules:
  - host: jenkins.corp.alt-chain.io
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-master
          servicePort: 8080
        
