-- -- 添加软删除 
-- ALTER  table django_celery_beat_crontabschedule  add column del_tag tinyint default 0;
-- ALTER  table django_celery_beat_intervalschedule  add column del_tag tinyint default 0;
-- ALTER  table django_celery_beat_periodictask  add column del_tag tinyint default 0;
-- ALTER  table django_celery_beat_periodictask  add column creater varchar(200) default "";
-- ALTER  table django_celery_beat_crontabschedule  add column creater varchar(200) default "";
-- ALTER  table django_celery_beat_intervalschedule  add column creater varchar(200) default "";
-- -- 添加creater
-- ALTER table django_celery_beat_crontabschedule add column creater varchar(24) default "";
-- ALTER table django_celery_beat_intervalschedule add column creater varchar(24) default "";
-- ALTER table django_celery_beat_periodictask add column creater varchar(24) default "";
-- -- 添加updater
-- ALTER table django_celery_beat_periodictask add column updater varchar(24) default "";
-- 设备导入
INSERT INTO assets_devicetype values(1,"物理机",0);
INSERT INTO assets_devicetype values(2,"云服务器",0);
INSERT INTO assets_devicetype values(3,"虚拟机",0);
INSERT INTO assets_devicetype values(5,"Vpc",0);
INSERT INTO assets_devicetype values(6,"Slb",0);
INSERT INTO assets_devicetype values(7,"交换机",0);
INSERT INTO assets_devicetype values(8,"磁盘",0);
INSERT INTO assets_devicetype values(9,"存储桶",0);
INSERT INTO assets_devicetype values(10,"数据库",0);
INSERT INTO assets_devicetype values(11,"域名",0);
INSERT INTO assets_devicetype values(12,"CDN",0);
-- 状态导入
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(1,"运行中",2,",Running,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(2,"已停止",2,",Stopped,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(3,"启用",12,",online,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(4,"停用",12,",offline,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(5,"配置中",12,",configuring,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(6,"配置失败",12,",configure_failed,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(7,"正在审核",12,",checking,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(8,"审核失败",12,",check_failed,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(9,"停用中",12,",stopping,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(10,"删除中",12,",deleting,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(11,"急需续费",11,"",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(12,"急需赎回",11,"",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(13,"正常",11,"",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(14,"创建中",10,",Creating,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(15,"使用中",10,",Running,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(16,"删除中",10,",Deleting,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(17,"重启中",10,",Rebooting,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(18,"升降级中",10,",DBInstanceClassChanging,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(19,"迁移中",10,",TRANSING,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(20,"迁移版本中",10,",EngineVersionUpgrading,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(21,"迁移数据到其他RDS中",10,",TransingToOthers,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(22,"生产灾备实例中",10,",GuardDBInstanceCreating,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(23,"备份恢复中",10,",Restoring,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(24,"数据导入中",10,",Importing,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(25,"从其他RDS实例导入数据中",10,",ImportingFromOthers,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(26,"内外网切换中",10,",DBInstanceNetTypeChanging,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(27,"容灾切换中",10,",GuardSwitching,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(28,"实例克隆中",10,",INS_CLONING,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(29,"已释放实例",10,",Released,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(30,"In_use",8,",In_use,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(31,"Available",8,",Available,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(32,"Attaching",8,",Attaching,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(33,"Detaching",8,",Detaching,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(34,"Creating",8,",Creating,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(35,"ReIniting",8,",ReIniting,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(36,"All",8,",All,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(37,"可用",5,",Available,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(38,"配置中",5,",Pending,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(39,"运行中",6,",active,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(40,"实例停止",6,",inactive,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(41,"锁定",6,",locked,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(42,"配置中",7,",Pending,",0);
INSERT INTO assets_devicestatus(id,name,type_id,description,del_tag) values(43,"可用",7,",Available,",0);
