apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdb-frontend
  namespace: ep-devops
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cmdb-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cmdb-frontend
    spec:
      containers:
        - image: >-
            prod-harbor-registry.cn-shanghai.cr.aliyuncs.com/prod/cmdb-frontend:v1.0.0
          imagePullPolicy: Always
          name: cmdb-frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: volume-1643189767922
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: cmdb-frontend-nginx
          name: volume-1643189767922
