apiVersion: v1
kind: ConfigMap
metadata:
  name: upstream-configs
  namespace: sso
data:
  upstream_configs.yml: |- 
    - service: ca-server 
      default:
        from: ca.corp.alt-chain.io
        to: http://ca-server.altchain.svc.cluster.local
    - service: phabricator-service
      default:
        from: code.corp.alt-chain.io
        to: http://phabricator-service.default.svc.cluster.local
    - service: kubernetes-dashboard
      default:
        from: k8s-dash.corp.alt-chain.io
        to: http://kubernetes-dashboard.default.svc.cluster.local    
        #options:
        #  allowed_groups:
        #    - fte@alt-chain.io
    - service: summary-dashboard
      default:
        from: summary.corp.alt-chain.io
        to: http://summary-dashboard.default.svc.cluster.local
    - service: miningops
      default:
        from: miningops.corp.alt-chain.io
        to: http://miningops.default.svc.cluster.local
    - service: bminer-operation-webserver
      default:
        from: minerops.corp.alt-chain.io
        to: http://bminer-operation-webserver.bminer.svc.cluster.local
    - service: bminer-operation-webserver-staging
      default:
        from: minerops-staging.corp.alt-chain.io
        to: http://bminer-operation-webserver-staging.bminer.svc.cluster.local
    - service: mining-pool-webserver
      default:
        from: pool.corp.alt-chain.io
        to: http://mining-pool-webserver.bminer.svc.cluster.local
