apiVersion: v1
kind: Service
metadata:
  name: cmdb-frontend
  labels:
    app: cmdb-frontend
  namespaces: ep-devops
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: cmdb-frontend