from django.urls import path
from assets.apis import assets
from assets.apis import assets_management
from assets.apis import assets_list
from assets.apis import summary_total
from assets.views import websocket_view, test_celery, go_ssh, run_one
from assets.apis import business_tree
from assets.apis import configuration_centre

urlpatterns = [
    path('v1/test', test_celery, name="test_celery"),
    path('v1/zones', assets.ZoneInfoView.as_view(), name='zones'),
    path('v1/device-type', assets.DeviceTypeView.as_view(),
         name='device-type'),
    path('v1/device-status',
         assets.DeviceStatusView.as_view(),
         name='device-status'),
    path('v1/idle-assets', assets.IdleAssetsView.as_view(),
         name='idle-assets'),
    path('v1/idc', assets_management.IDCView.as_view(), name='idc-add'),
    path('v1/ws/<int:id>', websocket_view),
    path('v1/machine', assets_list.MachineListView.as_view(), name='machine'),
    path('v1/rds', assets_list.RdsListView.as_view(), name='rds'),
    path('v1/disk', assets_list.DiskListView.as_view(), name='disk'),
    path('v1/can-go-ssh', go_ssh.as_view(), name='can-go-ssh'),
    path('v1/domain', assets_list.DomainListView.as_view(), name='domain'),
    path('v1/oss', assets_list.OssListView.as_view(), name='oss'),
    path('v1/vpc', assets_list.VpcListView.as_view(), name='vpc'),
    path('v1/cdn', assets_list.CdnListView.as_view(), name='cdn'),
    path('v1/slb', assets_list.SlbListView.as_view(), name='slb'),
    path('v1/switch', assets_list.SwitchListView.as_view(), name='switch'),
    path('v1/summary-machine',
         summary_total.SummaryTotalView.as_view(),
         name='summary'),
    path('v1/tree-data',
         business_tree.BusinessTreeListView.as_view(),
         name='tree-data'),
    path('v1/tree-machines',
         business_tree.MachineTreeListView.as_view(),
         name='tree-machines'),
    path('v1/environment',
         configuration_centre.EnvironmentListView.as_view(),
         name='environment'),
    path('v1/project',
         configuration_centre.ProjectListView.as_view(),
         name='project'),
    path('v1/services',
         configuration_centre.ServiceListView.as_view(),
         name='services'),
    path('v1/inner/machine',
         assets_list.InnerPostMachine.as_view(),
         name="post-machine"),
    path('v1/inner/slb', assets_list.InnerPostSlb.as_view(), name="post-slb"),
    path('v1/inner/rds', assets_list.InnerPostRds.as_view(), name="post-rds"),
    path('v1/inner/disk',
         assets_list.InnerPostDisk.as_view(),
         name="post-disk"),
    path('v1/inner/domain',
         assets_list.InnerPostDomain.as_view(),
         name="post-domain"),
    path('v1/inner/oss', assets_list.InnerPostOss.as_view(), name="post-oss"),
    path('v1/inner/vpc', assets_list.InnerPostVpc.as_view(), name="post-vpc"),
    path('v1/inner/cdn', assets_list.InnerPostCdn.as_view(), name="post-cdn"),
    path('v1/inner/dnsrecord', assets_list.InnerPostDnsRecord.as_view(), name="dnsrecord"),
    path('v1/record', assets_list.DNSListView.as_view(), name='record'),
    path('v1/run-one', run_one.as_view(), name="run-one"),
]
