apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: sso-proxy
  name: sso-proxy
  namespace: sso
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: sso-proxy
  type: ClusterIP